apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-basic-auth
  namespace: flux-system
spec:
  encryptedData:
    auth: AgBS0LnM2cBPLP60dI+2yJjmTfDBGRijvVGv20+hENzJG/ATPA7oA3IF4n/TP/rJluGWRUZPlVDR2zFL/wDp8Wo95kkQ6arX3J2S0BULUiSplTuxGNaupqTH37Tum+ZLjpBzu2MCm2HgaO0tu9FHcZjpan0piBynjFmzR0H3M27FluD+HLtAMg6YpEcOeL8TcPvOsYXLP/v2d1oGNU5mNaGfHD2anXW92lTbIFnLQ4AFETlrgZawZYx4H2aMBm408VLVvtOpV+eq2cilcW+9LHGZ3EAerHEEEY2ARzZMjkvbJ54PqY9m96Q1zKi3QgxybHOjL2n7b1IE4mqLE7hpyoOAodr5mofBaXQr0T5DjmdKPYlpw0NYpihxEfuDSYMRD/jkP5xjwUVUvl0DfzCnTjTVB0Itc9Ls76KBTY8duMFsz9iKWdA/GzQ2rrDvFQu2gzlR/fHvNteAG/6k02kIPvndX/bPfngY2zBfiF2Iqy+g+m/Mjk50bczow2Fad8NP+XfzCq1FoJPrOXMT1/GAvuPvsxRU/kCUVheInZfnppQlHAJxTthQ+I051efP22w0aKruYjMKv563i35GtX2ama8WsdCIHnPVxqIyHpApUgLqwYsimZQ2w3IIaivWBL72w9XkAX14kaazBP6B7dl25ICyYErF1tC0hloWIoV0gNocPN5Jk62yl4TACCzuYDBN38ouaePBHwoJ+lrfbXdQDEhNVCCuizdm2mpBbDUifNJ4meitpUWvdZKZn/CUHA==
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-basic-auth
      namespace: flux-system

