apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-basic-auth
  namespace: flux-system
spec:
  encryptedData:
    auth: AgAjldLzYDpOslSuq9G0k8HhduxDZVxKhkEgaTW2bw5RniOHc9TIQIWQ3L0Jm529Dcen85jSeTIBpT9dgJSZ1mnB/BqxgkKh2nHIRAl7owOY7OXSa0PgWsbrq9pV4M3s5iaik0AX4T/oK5A6J+c04HSm/IWG65wm7Q4sgW4euKYZNPqZLZzFxI/pUzBzyFnWHFo8x2XA8C5L2OllipPYrJYGPvdXuW3rmuo5kbg71bGT3Zp2WNhixA65ECHPNisOsF4xol0DxQMF7Q1CKmc/fR3+2QRFqKmrHSG/X3TRTXadOnojBhQCsVUblvvgLAg0sNxPkyA7DQu+kip6QjZE9y0Sgzjdnk1klt49Ou8W1qd5YWEipYvCmYqIXyZgmITwxVtJfpGEC6KMNBtf36DGLxBv6BehtmVDD08ct9b/iT7XmfNsnbJvU7h9rt7TLn3Ghh/0rGP8D+kGcCrWkoaFbLDsgAxy0M5jS5cWvGRofyeSJz+YeYBv0UJZUv86cRBoMVzsNe84tHEc83DroKN/y7RQqFX2Hvq8HrkwG5yHW2CTeTuIeNJyatDfM5xq/azjAAlOxF1K3yxnFEV4DJhQGCtKUZzE8Oeh9+UntY6AbbiCrsJe3NELLnnfglc1Ia9MaMNnBBrWa0FSSL30qiQLr5rJpw7JfF0ZSfP5xspDgZMRyFP6nlKksIFvNKqeptVo8wVuEG9XFEY2mvPRSEcW6b1u2NwouL20QOeSYbICJtsWl9NTUNRPrsyJ66aERw==
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-basic-auth
      namespace: flux-system

