apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-basic-auth
  namespace: flux-system
spec:
  encryptedData:
    auth: AgAg/qv/IkUdVCouMUi8ff+FQbBSFAGHPErMm6JE0t+F2lQDHgnq+BDbgab7S2LHpTVTusWh+sSZBPGVco5/2+FQ77CfNPYUidQtt4tv/rx/h9ho/6DKiSd6GcG3VwQJAGTFTZUTLXVj8BIdtoA0ply1xS0GVPUwub24P/uRC1AMw8Ax61VDVtEm6rG27H4IqBcQ+a1MDnvQvJf0RcHwnciBAREIzuRqCoiqmL8rsvCtLTgIjWKrkbcpGCzG/uu/M6RvRU6i8W/iTgdFOGvaxrD4cu/q2JrYFX/4AuaFLodlEfN9igwNzWRdunAkvlzBgaWBER7HTGVtHuqdIOKmXHihRhLPPYrgJc23Dhx932gZm1AVHoi+9h4I1jJ8yYmSBTkBdEjk5C7D/fKyZqEITHEu198spuGiLpHCVUhXhRA3frFDleEaGRX6RcE5uN6XiKsYP6zzGrIHsjkKkE1prf2Kqyo+APL65fRmK3NY6UzdJjrFKtAmNUdoPzF2MvlMYlRdpTL7lW3z0B1epPzopTVgqhinz0Td6jQGIm4I/m/g2GjHMKxY3tofx5FtDh3adaMsAg+3SqjWa8wQYcjbPnUhcoe/MUhufyB3JzEj3Bu0plFmYR23dEbLvEgUWb6TYy7wnrSrcqVOLVVo5UVKYfBxGgoVQE7zGvJTwZkxEjhUsqcOq8MgEiryZe1KPAu2R2Hkqt+dD4INnDnz4VuyqWXVBmkTD+6IETzapzZPM1UL3dSxkktwrFawD6qNgQ==
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-basic-auth
      namespace: flux-system

