---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgAbJRaKNZ9aFzpi5penQRl3ydRSFdCLtC42Pp64RepVmhrnlwDqAolgVuWpXvPlTD9Tq9QsNadsliFbYkjBStVaVrs7MMCYDGqT2kKPJe6wfhb5nO9LyeRf+kiEyJtFfJuaa7rriQYDdFBKEP6+WZCvRgz49wz4ZsVU3Dbhsr8D83mmOfExFBJseCiydTJGV8s4V1sANjN885rX3vVC0lfEgCEzrn2ywQNxXAExeZWI9gJ9P1Fj5wqirY9F0AdwC/ihmcPBbkTiN9nRuH0eg1yancB9ih+eEQNaBRlTg0vBk7eMLV9uAuHTe38EVwDdEQo+CR4QwW0shF+pt+qDmEO7PBEPhVuv4XO3hr/lN5ua4D7opyeYBD9zArAExqq9WtVWpk0ZHgcHZ6tFLNWPN+I1hHCScoQxX8vcQjaJXFTeLbPe590P7Pk2JNvSeC8xHEa5X4h6HxzTLgYg1WjwLUGFolkdE33ZXgm5meqx/Yku3Njxa/Dpilicec6oOQGQn0AKLzZa8RRpweOONPXETSz2KA0HDIiGroj9i5hRYzjBat8SYjvKar5CUc5OGgzZ+p4+tC++YcxDCiZyCLy7SRH6SNfF1UecvAt9axpL537dcDlhF3l9/hwJPDQUytRwRtU74k8JxTWlyE0j9wO25+jtrMbr5ufugviP7/vbIzjhSqEPzlRy+OOjZ4KOGH00SQBptx+Tger7na8QvR4KJDa8riH2dOkYuMDmZ/PSX+jAfJYlihU4f4AEEilPGw==
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-basic-auth
      namespace: longhorn-system
