apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  url: https://charts.longhorn.io
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
  valuesFrom:
    - kind: ConfigMap
      name: values
