defaultSettings:
  allowNodeDrainWithLastHealthyReplica: true
  orphanAutoDeletion: true
  backupTarget: "nfs://tatsumaki.marokiki.net:/share/md0/longhorn"
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
service:
  ui:
    type: ClusterIP
persistence:
  defaultClassReplicaCount: 2
longhornUI:
  replicas: 1
longhornConversionWebhook:
  replicas: 1
longhornAdmissionWebhook:
  replicas: 1
longhornRecoveryBackend:
  replicas: 1
