apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: netbox-postgresql
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox-postgresql
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: postgresql
      version: 13.1.5
      sourceRef:
        kind: HelmRepository
        name: netbox-postgresql
  valuesFrom:
    - kind: ConfigMap
      name: values
