apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-postgres-pvc
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
