auth:
  username: "segre"
  database: "netbox-postgres"
  existingSecret: "netbox-postgres-secret"
  secretKeys:
    adminPasswordKey: password
    userPasswrodKey: postgres-password
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.0.0-debian-11-r13
  debug: true
primary:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  persistence:
    enabled: true
    existingClaim: "netbox-postgres-pvc"
  
