apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1m0s
  chart:
    spec:
      chart: prometheus
      version: 25.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
  valuesFrom:
  - kind: ConfigMap
    name: values
