apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: values
    namespace: flux-system
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - prometheus-pvc.yaml
  - alertmanager-pvc.yaml
  - sealed-secret.yaml
  - helm.yaml
