---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    slack-api-rul: AgCNZqs0kFwD7bi7av0ScwkdLfeSZZcEd+3sgetsQGVtgvb4gAMeKGWuQuAgoaJOXlKhktLyuZf22bjjtUxFkIUHZGy+KKqCu6KjGFV9NtP7DkUNSa0aerhUuYa0CujtTyjTapAECT1gPRvIE2lcdzcBUjSfEs3ZEiAgNz+Xq1Z+3qzgwlXAZt0mKZDm8XkG6k7wDBabLPA6ma1bCXj9R4ik8W2jsVMSqprrqOhscw46Pe1sxNIlEL+V3SABaC/eHHT3zDWXwODooVisjgL7cSA5aMZUHvB3TzyehqpQJL9pdJ884qRd91205FGjaubd/PPgvWnEDuhIatF4LCQk3MoDZ6bnzjprOO3TFVjjcweZoqcR57fYXy6aE6OC+JEt63+uIYqkf9F5TSuz9Vi3S69pG6jGATCJzkiU7iR7zfM5VJi+STyFqccIyrZ0LaTSmfxVHAUIwn2mnMsfJ7m1F7YSYnXZAKpaLR4DCqP+A+bTU9JcyOdJo2rZvDAnNqCe6ocqYqYEtcp6mzV0UZy0GA4fUOi66yDWb2lLOlZi2WgbgZ5V1g3Ra4bwKHShAXqYM/WKobV9RB02rAvJo6Qgwc0t8Vx+Cduclzcre9kGV5BnbE5Vn9lGV31gZL67eshAA/IWwfc9Zivk8CnJzhnJDXi4x3/vr6UbKgJpf2QyB3RlNrpprQgiZDPcMmCIyJDYMcKf5zuClaeNCwr/6SPBsfCJdwXnV4PMBRXzFpP2qT8VK4WrAc1FG/Ob28ssil7rHaSpS5xILDmXdsanCVt/CHg5QMOKvhpHr/9HepPCe9dE
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: monitoring
