---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgBVQWB2MdU+nQfA/aYOo5VgesOLILKqPqTO33x0fvXmNgoNsAr2ZesMcdWr6FrpCNbjvTEMsRcUDK23XsJiIWqqrI/eeCaTb8+Z8Vcc/hVyhEYs8yNjHeZ263NmoITlUg0AaUI/VKgpy99HPc5DRE7ULKjLDYRmi98XPwT1Z0QjRBQAu/iCvBxxVlzkWly1UZKkZgNrVOqeKlMAaVrDeEpWg9Qn3z6i+WiSJW5KMmWWRsBZym/RGNHeuSt0LoDrY67Ar3/VEr5lQyl01Rh1BDfzDzmsgbj1pkZwEuqNqkyuLZJFKgaxFtcEuRcuJx3sZ7gRsl9ADlkeU0WhA1SMQYSXT+y49pp4jeJx9GJ/9ltYPd4oZs9nrxT1dc5p4a4kTPvs1A8t4yiVECrKEJWtGOHY8zJOQxrsna3sKSi4uqFy1cWLBGYnlDCKNdzjwxJPC41MKueYt0dgD5O49rBHXsjVp2OoeGD3JIUi96a6utphQR0trgec/b6hEmroQ8JHsTwV3015RsGlMENGPukM64eWCdpDayMXqo3p5j3gD0QYLmAFggta2gDqRKBaBf0ZEE69fCPOi1J8V47S+1cqX+kjYum38+dWXt1kvTJMETMFCsufcZ/Im48I6s2awAKH207Q4/0G+JEcYRHT+81jVzBLkf/J5JEQeDGId6J/Y8TM+ojO45yd1lr3+QI5rVQyMU9jCr3SP+4RzRWtZORguW7URes9K2e8lBbotGkHO7ug82tNPr+ysMHZl+fBvw==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-basic-auth
      namespace: monitoring
