server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      meta.helm.sh/release-name: prometheus
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/hostname: prometheus.marokiki.net
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: letsencrypt-issuer
    tls:
      - secretName: cloudflare-lets-encrypt-prometheus
        hosts:
          - prometheus.marokiki.net
    hosts:
      - prometheus.marokiki.net
    path: /
    pathType: Prefix
  persistentVolume:
    existingClaim: prometheus-pvc
  extraSecretMounts:
    - name: alertmanager-secrets
      secretName: alertmanager-secrets
      mountPath: /alertmanager-secrets
      readOnly: true
  alertmanagerFiles:
    alertmanager.yml:
      global:
        slack_api_url_files: '/alertmanager-secrets/slack_api_url'
      recievers:
        - name: slack
          slack_configs:
            - channel: '#segre-sysop'
              send_resolved: true
alertmanager:
  enabled: true
extraScrapeConfigs: |
  - job_name: 'node'
    static_configs:
    - targets: ['flear.marokiki.net:9100', 'ikazuchi.marokiki.net:9100', 'manaka.marokiki.net:9100', 'aroma.marokiki.net:9100', 'hikari.marokiki.net:9100', 'tatsumaki.marokiki.net:9100', 'anna.marokiki.net:9100', 'takenoko-1.marokiki.net:9100', 'takenoko-2.marokiki.net:9100', 'takenoko-3.marokiki.net:9100', 'takenoko-4.marokiki.net:9100', 'kinoko-1.marokiki.net:9100', 'kinoko-2.marokiki.net:9100']
