apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 10m0s
  url: https://bitnami-labs.github.io/sealed-secrets
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1m0s
  chart:
    spec:
      chart: sealed-secrets
      version: 2.16.1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
