---
- name: Collect facts about system ansible_facts
  ansible.builtin.service_facts:

- name: Download node_exporter for amd64
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: "{{ home_dir }}/node_exporter-1.5.0.linux-amd64.tar.gz"
  when: "'node_exporter.service' not in ansible_facts.services"

- name: Make node_exporter tmp directory
  file:
    path: /tmp/node_exporter
    state: directory
    mode: 0755
    owner: root
    group: root
  when: "'node_exporter.service' not in ansible_facts.services"
  become: true

- name: Make node_exporter directory
  file:
    path: /opt/node_exporter
    state: directory
    mode: 0755
    owner: root
    group: root
  when: "'node_exporter.service' not in ansible_facts.services" 
  become: true

- name: Unarchive node_exporter
  unarchive:
    src: "{{ home_dir }}/node_exporter-1.5.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter
    remote_src: yes
  when: "'node_exporter.service' not in ansible_facts.services"
  become: true

- name: Copy node_exporter
  copy:
    src: /tmp/node_exporter/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /opt/node_exporter
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  when: "'node_exporter.service' not in ansible_facts.services"
  become: true
