apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCnOTAHO2vwXkuQULtj6JwpmlpDHA9RkESGEq6WItJRXm6alL/OWQqnazlPBVW61zM9MRh9Ll1qWLTNDQWGTcw9c6NOPop+qDn/RjyR3bKF2bdldkHBUoM74xDY6UEfElSAWhhzmGUXNQDql2jK8Px3MOt2MsSRwlSnU2AAMp6C4AOnJgnY1PyU3zyz09LozBi39z0SRvgzaxziIYPbAiqWewEwkqbUqhXHcrttP+JNGmz/dMfwKMWWgz37WP+ebPxeVzjmkagGAj/CWgl1VFr0u6jDsgq6BpV6NGkvswzxHOeRgdkb7K4bL3gvWUid7y2SAy/5e1rxxkueWWTEulwyHfBWtBq/prWy9UDi06sMFA3UfQvLktfV7H5gI3AYlNJBYDWXYtdtWUgE+qbVcKc0tMxNhsD1vfgdRHU3SECUz5OM1YGWRw3rpGqpoagIEu8JNPi5WVODdF0wLV0cEalxGMYPSX1zI3ZJtNA9ULc1mw605gDPUf+/Vw6VyPxC1s8rjR8PDP2rKrVKatrh/WDjtTXHcgmcWmGwZLHYliqQBR/tSGjub9wRZQvllT1WhajdOLtGYInPZQk15dkoLibOjCuBTqlnXI7L5PZx90y3zlxCfFxGeCGXibkdpnRtkihMoSGpjrbDoVLn6AlCI93NITOZTteUeZeDD0F50t8Y+8NkpFe0O+SnXhGQ8dgjOOLZPsVCfTu9ZUhryy4PJqqWafc3UVpXKRdZDQv1pFg8bw8lZn+fXBizQ8UUFVD6VFRrftKuHBcfv5XJeuOkChL2/drTcK+nCXniBmluiR6P
  template:
    metadata:
      name: slack-url
      namespace: flux-system
    type: Opaque

