apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-slack-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgCQeAPHqM8FpX9mGctA3itJ4AbsIYoYWgvpiJhVub3RYcKADiop9gsknNRgxahb+mt92nhrdu9KY4sp5mB3oM9j4RDdbLcxSTfBuw3I4Lj0rW5FFwagYoTKp/AUQvCKIOvB4BmhmVjtCe3I/A0qfxSFrZNq3Qkijn4Cn4kSEh4AsCuwirknY7WQpoYEDseX0eRo/F5C+O51Gw7kCQyXR7NP49POWLym/jL7C7O1WAHXGI6WiXjeoaqIaVWtSzXSn5C6/R1B5FjtQexa63Wg4fdVSat8aNfPwnXzU49k4MMrwAfG8zF42UxEeILWP7deUXp1MEjXxyfgXweTRhTqOzPCsxf9+7wJFfAm4/Yx7o4Hv4SoL2UrnJ9EK9s94Zwji50vODys/pxpwq3pRb2+qGO4f61894l7uFaJAt4frgPX4NRsC0NwgdaYZ2w/2mOl5hF/umDTlXg4uffTvuB45MGddFiBviS7iYrvO2gm8PPXRHHj+PFQDo1YQsM+QWO1kKr3CjTRmJsV5YGSkZsqZLQysEiwq9EBH3pG+wotFJu57jUdxdAq5ZIeCsXQRRVIZ5JLN706z6f4QU5iBwhZw1phHpIqWpqIKlYHp6PLY3Jp8ZxEYkExJ6Od1wh7oqagpv8Kxeud0wZSk2oGWML/k/WLj9MkP3SrUWbfiEaR+Cctbf5PN4HJdz6WOlnYyfAcUGllNH/J3NoAyfTS6KCoJVA8NjPifGcirlF0hGIuXaR1p9nh3dNTBtA34++ePM2rm6jRYxintIHJ/RMPlpgiVk3yFspb/e7kiWseILgRfWkK
  template:
    metadata:
      creationTimestamp: null
      name: flux-slack-webhook
      namespace: flux-system
    type: Opaque

