apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-slack-webhook
  namespace: flux-system
spec:
  encryptedData:
    webhook: AgBuChEwcOCOMniKTZKzBI0VMU2+qtnrk6NbNO+MtX1/VeSSUyEWlY8tQivh9L5BRscZvKcPbCKXor7tBIBDibe1B2enyd+LlSgkPdAHH0UDL9Y4g2yLN5tKRr0GyE4V3+9QQKkb+DSzzp5Ys9PXud8TMAWxuRKK+ZUy6Bz5qn/w34rXJ2iFi0FMyE6JJDW9a22+0pJ6Lmsw9ssXxPSwu4uAxzpuVrLE1m8d3dml3u3opCI9t6kAaprXTeuSNDsZvUdRLw1PZp/SMV2dpVZqwHvNQ7d6rMRtJQcw2ZrClaK7wg4Z8Xf1+w6A9/yWgp5e53G5t0pT2x5JfbUJvYiMF4lcsBzPx3hFvB0LMM/MXcsNFffcrc/7uVm+gT7w5QMKcnV7CZ3a5O04TqPChOucNDsAIt9LkAlNyXokrelFgy/1qgak2OUtf+jNYjg8J1F8obTSbYURd5MLvdzNYbc01KPgmLCUzjww7ti5ANCu7vtF16uycV7S8FepbNKFmHZTtk59HkgnFc54HNga742Bck8x1HDPpfSmq0nKB/aACmpJRqgpFWuBMCPY9MK27uJ1yUwm2pfYaIY4tFaHE8eMq14duo1WXOMhifiePvDHF21fbUn0VvYG3BYIQQqRlDPtN4dflELRPUxYgBXRuxVmq0+OO3NB6N+OiW1jHRKdnMDtCg0MFWUrQY6RekvkHgcQKM3/yxQIs17PFE6/vXV8bX2F/kmBCqAB3b4zAbe2WJ9nV5jgUAATCa6/rVQUCVoZ0sxNZ4e9ISBsrQ2stb59LO8xD4x9uvfimBrys3XkuoRh1A==
  template:
    metadata:
      creationTimestamp: null
      name: flux-slack-webhook
      namespace: flux-system

