apiVersion: v1
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzMjFSU0o1L0IwNjBOUlc3QVJZL0ZwcFhMNHBCZ2RWeFdGNkYyR3FIUVdaZQ==
kind: Secret
metadata:
  name: slack-url
  namespace: flux-system
type: Opaque
