env:
  TZ: JST
  POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: wallabag-secrets
        key: postgres-password
  POSTGRES_USER:
    valueFrom:
      secretKeyRef:
        name: wallabag-secrets
        key: postgres-user
  SYMFONY__ENV__MAILER_TRANSPORT: smtp
  SYMFONY__ENV__MAILER_USER: 
    valueFrom:
      secretKeyRef:
        name: wallabag-secrets
        key: mailer-user
  SYMFONY__ENV__MAILER_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: wallabag-secrets
        key: mailer-password
  SYMFONY__ENV__MAILER_HOST: smtp.gmail.com
  SYMFONY__ENV__MAILER_PORT: 465
  SYMFONY__ENV__MAILER_ENCRYPTION: ssl
  SYMFONY__ENV__MAILER_AUTH_MODE: login
  SYMFONY__ENV__FROM_EMAIL: 
    valuesFrom:
      secretKeyRef:
        name: wallabag-secrets
        key: mailer-user
  SYMFONY__ENV__REDIS_HOST: redis-master.database.svc.cluster.local
  SYMFONY__ENV__REDIS_PORT: 6379
  SYMFONY__ENV__DOMAIN_NAME: https://wallabag.marokiki.net
  SYMFONY__ENV__REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: wallabag-secrets
        key: redis-password
ingress:
  main:
    enabled: true
    annotations:
      meta.helm.sh/release-name: wallabag
      meta.helm.sh/release-namespace: article
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
      # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    ingressClassName: nginx
    hosts:
      - host: wallabag.marokiki.net
        paths: 
          - path: /
            pathType: Prefix
            service:
              name: wallabag
              port: 80
    tls:
      - secretName: cloudflare-lets-encrypt-wallabag
        hosts:
          - wallabag.marokiki.net
probes:
  startup: 
    enabled: false
  liveness:
    enabled: false
  readiness:
    enabled: false
service:
  main:
    ports:
      http:
        port: 80
        targetPort: 80
