apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
configMapGenerator:
  - name: values
    namespace: nextcloud
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - pvc.yaml
  - helm.yaml
  - sealed-secret.yaml
