---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAtYNXgG9INgAuFiLrecrz/wfmc40pgUZTP4Df7Zxxt5f97x+tjcFnv0/ifVjp45bz0HyP9TVNsRf1SGjM//M2VlY/+y0Zz56vrQDc9VTuFwCf0vNKSFcsQCF7Li/K/XXGOUtRHKbDAWli6l+ayglbN2F/k1wn2a2qqh9fWnnmVAsjGVQuLOJxw2J0yK1s1nduGuN2NRzqap/9KstJcCkNfz6dFLuNC2j7EaDFrotaZ0GT/0hpqSBMVrEwyn3Tz/uCT5mUhDXWyypQRebTBvjrgZMSIlwurUWIyAapU3oGU9he3783DMkl/belXaIzXppAwH6mcT2/Vcw0Yai+cEawIV7xMKHg79cnKjzCpqFoDcAjZybK9jGTobvkQ6JVjkpQ08I6+sQW3XVzdLYBkM3xA3noab+SIaV45kc7jG+BWYwiODWa1IQ1JEH4d8IkHVd3dX4uzvCf3gNRfFMmoYD83QwxytDTfeblqlWhpr/RWPgtCnEe9JoV47sCXcbiRKmdwzCcdyU2f8Dj7ve4Jpe3526TL20RpHGaSrtOAt3y+HIz4xo3tFUY0gfwTHyvT8qKW0HHTEDTnJEI+3A9x44hWAX3lWc2YlxhADJE9aOjf9URkqfr8JMav+l/DV79BhWL5E94ZMBKkLnwuxdx98X8lAKm0v/ZERBRv7JX+o+MzFbR/R3AD5FOEZKwvwAK5Ozg0fDvWyIMXrlVPVnr1
    nextcloud-username: AgA49Dd3S6ZXCECu+aeB79a5/GGWttbK/wOgMMuaUrtT8lkTIH/NxMLoq0H6RUp0Au4oE48GygfluMiClOgUI9rL2ea7+tt3+eyr/O9CUlti5v17hkAJCfqnPOBbLGyoj0ETj1rbW4/7JuAEAKs0lnP3MmFYiYiegrxsCl35gploFGIYitVjJP19YILF/TYIcR0+uRSwZr0BoU7zZ8Lk3LFe2UqAyIdvXVWCtSXfsDonBFUzGY80UzTOvPMhPukKOSRdBcFtoQEd96Xmgh2KZui3T4fuVyDyo/utjPLRKHjsZeKPAUbcHd/wzdKH/OWpMwFYJazTosIqmSgSE6Ag59I8A7KIupBBhmt22WGOXJj0yUHP5Tbn8yWfrpUcBSzHTeoFgmpr4uOKAe7/Q0w6DaBjKzo9483yqLxGPlnBSMNJIuyFOR41PmCkOkYBZm9VfF0D26tiwQRrBn4OFAyOC4Awiuz82fVwe7FJEcC33F8xjg9qDwEHIThRMbF6JaW1q8NNFrHXMgYfqZHN0LmY/8o45/c5EWfpCBmc/DViCV7BJnGsSrXxUF8xZNqRr/+8g5Z3pwDaw9kgbWeipDhlvdzerVIAkHQsPabzODMNvLoI3dlo6lvCgbqAVNQw0jelyS4TOxSV48igVFGuUi7nsKo+rrdvRo3rhx//L4JbdONouUlcF4WrqYejpgirF2qqjwl2g4+SyQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
