replicaCount: 1
image:
  tag: 27.1.3
ingress:
  enable: true
  annotations:
    meta.helm.sh/release-name: netbox
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: nextcloud.marokiki.net
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
    - secretName: cloudflare-lets-encrypt-nextcloud
      hosts:
        - nextcloud.marokiki.net
  path: /
  pathType: Prefix
nextcloud:
  host: nextcloud.marokiki.net
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  datadir: /var/www/html/data
  extraVolumes:
    - name: nextcloud-nfs
      nfs:
        server: tatsumaki.marokiki.net
        path: /share/md0/nextcloud
        readOnly: false
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql.flux-system.svc.cluster.local
  database: nextcloud
  existingSecret:  
    enabled: true
    sercretName: nextcloud-secret
    usernameKey: postgresql-username
    passwordKey: postgresql-password
persistence:
  enabled: true
  existingClaim: nextcloud-pvc

