---
- name: Install qemu-guest-agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  become: yes

- name: Enable qemu-guest-agent service
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
  become: yes
