apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    kubernetes.io/metadata.name: cert-manager
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    kubernetes.io/metadata.name: ingress-nginx
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    kubernetes.io/metadata.name: longhorn-system
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: netbox
  labels:
    kubernetes.io/metadata.name: netbox
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  labels:
    kubernetes.io/metadata.name: netbox
    kustomize.toolkit.fluxcd.io/name: namespaces
    kustomize.toolkit.fluxcd.io/namespace: flux-system
