apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: redis
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 1m0s
  chart:
    spec:
      chart: redis
      version: 18.1.6
      sourceRef:
        kind: HelmRepository
        name: redis
  valuesFrom:
    - kind: ConfigMap
      name: values
