apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-master
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
