apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-replica
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
