apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-password: AgAQ9Ak9Q2uSSwEtYlgru9DRHLbXLXQaij9Xn/heIFs39K0YKbWZwyuWnPRIYd2BadXTXbzlCTOH56gvIQhthp8fPwJuR2DRGnbDOc5if3lYwaK9qJRi3BQQl5Z+y+tx+SoeQbBU4kGjm7L4oON+D3aqUSznS4zobl4e/zuze6MX5IR91f5oBMoJKIKvSMEIJqvo6fD6kGbZTl0yKvy7f3hL9W9fK6xY7Nqviok8uZebJziCrvKXfT/THm6Lna7UliyBOFTXz+5h5qau8lrR1uIRpBnkLJJiq3XwyKmue8RVCIJeq7MijP5r1xCqBswRWNU3rBxqmyXCNp0gm/+CpzyzeGQCeU4rdqUtSr8c2x4Q5P4PgsIYdFEd5BcUP0AFPn1ZCOmFoTcKEJjvDOYwyPOXXreffp+esVvB5ssreQoCyrT71kHG0uTmPAesBLSdBAi5Hu89uIQ895lQ4CboSCnvTxKWCXD8OxrsjJQnOt3uKL/JTeMnVEhtmJtyUoof6JntY/LIrfVNGrK6JE+0L/pEFUCbV9ZJzWM8EGZrTS3dNqfXvatjL3iStW74SwOFk69xYjbMXd1gpNQLst93id8yfLdFf0rOsy6b790Qx80YxtXax34JJRcKakOy9sa9Cuxv051v/IbO97GkCSap6P3ryDNLhC9u5aKRJ/1j+PF/h/LQgWtFfhoqY18U8IuJ24SaYUuKL2MyFTYrwKkxJQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system

