---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-password: AgCUj4bibdkO/0TnDPBFBVtTvBBP04eBMCe8ooxM3sM9yWjJ2vY6AioRg1Dtk3ufzzUJ01CIqC3j33NxYxKqR3kIN1GzwqiQjEZonGlXY9C0g98gG8lFWuH2D9yTUfD3MKWgnwJrwdKBTWLngPwWQ7/WlYfQb9tTWY15TI4TjoLss3GbXVie6LIesR5W+Y2sY8hxGoMBT/qHpcHLc1+NMQMk2PKwzeaAHnCpJqFt6BdpreGrYtyEmECuQPJ6A0BMmLzuKjcwI96Vcudd+xJvJ2jlIDsHcDv6eXuZkYQ/FtkZ4585ti6BbSUWDiiK5tb2gw2nZ6CmtQwqABtY1k98e60AAFlLMmH0j2RvPwGTMcSHjjVVcd2CLxgXxktFBs+N5XxADC08yZpkng50vYcuB69FE54INj0lcWLre5ppYmnCkUh/5NWH2HE36Mk7jTPsyLXII69UDGTvJ7DiHvsdjNM5qBkg/phKiCC6Fy2+E4laGN0I4udikXs9GzOf86SZDB310JtXH/pEoAK73FTeIqxwcZ3tAhvnwFgWqPXdp+Otp3sBnZXvP6QS0dKLQvduogqjmuLDtSs8RkD5ozv3TM25IStRCQIpNxcN0zL2IDsxx7N9uO094E3+L4rfWfenedQQE1BiiGAY0G9Ipih80ASCqzVGOe0vQDVASjvgbzr4o0UGl4cgbMVuw+8vz6cHN0wVIEyPxaSEqJAwJ/Qjgw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system
