apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-password: AgCaiwN6H03FHr5qeGNcVmDdnuEFDDivL13jVIRIFzg1vxbNdh76aDJxXmP6OS8W7AcqOboQH3w+wU8gFRx6jD4GCpYHFrqjJ3CS2ZBUgviH/4ivri+A1sZl2hZhghkHPIvnBdwcbRxvk5btGoAkA+tFgFTOFg0Aor7xEWenClbOyOeASIieRdTEx6zqhwqQpj2WYMnKkCuM9ijT45CvKHp2DZCqE1KATqNWHHKmUqtYVnOxyImhDfnK2DnANp+oW1yqCn3+PsmWi0X0ZtmZmHIfcKFAI8awB471Yw2r8/6giia8LC2yLwffihXVnS8IyDiqbbZynjEw2ghUKHqmmyMLwF1YkGPxef2WcTzFN6TggPja5To5t0wTSTlCjba43TwjEBNnJXKuHLoufK5wNnDgsuJqnLKP6iptUj3WbWqSsyaphKXGoqtpb2pct9wSncm9fel/JrZZEoekVSCbJAjq7mAeA3VCCzWDpqR7rTONhHOLo6mlSoNl7yw02659TcAKzpaCkfwQu7a7CZ195AKK3R/pyycXWh9NMV2n/umtUDn4Pt6sngMuxrGSebHfziGtAUiVH6BrfKs8RO1ULm4qU8HDCFtL37zPGhshWdlYeVEcFwiCBvw7TTXcfzMJAHLWqWhdVmR9E84SWqbU2goV17dOX7bgkpRektxn5blDsqquHOPatgwlUQ9CZxm7cvvtX9qs4kaiLU5vt1QutA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system

