apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-password: AgDOVvetcMEx9UazWuxZD1JWHBR/0dPYONb3MrUZsXAaOfrvtlOU5Yz68fcN0V+hNvJdGY45BRXnMvnpLNkWbFDMYmnZLt+2I4HL17IkHgf0+/zJcjXZhwPDay6/6Xl78TaFDbxbSUXV3rmoInqpmnP27sNXH/J1WiJtCBtzEUstcdrSXUycjxHjsMDJoqz2nVxddX4xMgwh9gZQrlgQRSo10vMiK88ukR1WW978yZJUU3xtKxPAhSsGsfOHFAt9HIZl1kI6IL2A1Gaq3KQek/D2U1WRc/8l1lz4squTbvSD3KI1ZXhsl4WMAixGYnanKj8l8QZo2So6X4GCx1XtW0T4pJz5lUbIks2d6WLWzZAEyWnO97N/Je8yrV722uQy7w5Ib9wo4gkzQUZasyz8hjH2WLuZLSWo60Yb5a2/0W387jRgqsynaRijfHrPa9nKU3MOTWYaydKKceyO5fgswu4czKTvF955U8OOSWsQoKEX7z/ioyjNlY6C2l/n6kkBue/UnrgMl+EMmLX4KYQhbwIiCGdJvqE8PPHV+rt44yW3CheIGFgonTMvExsxbmGONtj7HDdVnpJ5QUQXd4ba1jI4k37xWz3L2hHXAIof7fDDR9osMaL138fH6HU7hloTuEKF/T2Nyp/21HTeAnuGR4sSvLFvll0rbp8it5ip6o335Z/OP6sdXz4v1TvmhoczBqoGwSO5Y8acGa6yvPzMQw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system

