---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-password: AgACDzaq2bhNeiXN1VV2MneaE/SOYcENZjfuhrfQiOT4PZHLt5ETaohgYrFUycm6CkOzdRRlDeCUBVdo/bvyUm8r8LFQjsPaxtSiR5JLZCdxqjpmC4ODyn8AJ+KiwLA3+38dVb7y/PQyxmzjUEGlFXB3pgiJKaV+uIRrctZuxtMrL6f/WEHA8sUdCeaLPHT6R9urLc/dWUNPzH193C29q67HNCAlARqoliNkUsZjclvgtWA89cgpQSSZTur53YuBERvu+vJyLn8/zZrzddGpHmHvARU0/ls9hiU0UQAOKWpcNEZ30R/oqUleMiwasMa68SQpxHjNI4qGPmn7dgWi8Xx5S+f/nuBkcSV85P6zVRlqdwq7a/VYWN58fG7CFV8Z3xX2VUu6Vqj60cu0q6osDBiLdrCgVcFq3XK9EM5HwbylZmmmOsiDhehmOb2gMel6dTqrUODKljP5xRg5+acqXDau6iivkPCZH/wqK0Iw+5sivuszq1Tj8hq/Et2mDLZv439329b7a0NGwkqQx4TkPbaRoxL5TKKHdc4rEtqXUsEqVC4Ind14zFR1O0l0e1PE2JMIDQGllZrXWnoeVmempkfc5oYyNOlxV+GQflUroIkWpn+M5CJfe9xUJkqtCyN4yBXVHs3u+Ui5ETx+zPCgcjMKeuuBDTFhzSPenejhRZf9EpQJtKGis/S0D7/Jui/wnXOOcVa6SYZDqxH8pA9rNEwEOcYJT08Ny7b307hkWQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system
