---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgBi//aZqyHUaaPJiA/6m0/0ydxcSkBkaPMuSJ03ytXkZQVuQfWtjeymOp3yKc106lO6xMdyU5hq03HvBJX72+YPLmx+1cPRQ3yVc5NUNYWRCrX/TwbusDEl/fSgawjC1ccFs9Mgmdqpk94gx5M5guXOWK7eoL7dMYnxJyu+2z4XZGCxtD+An/TZTbc3/hPAYUB0ykX7N8fzWGsIPZrYTl25Npo++OSIVxf+RTBYaxOMOu3itsHb2w9gSGzWmRUVu1FrI4RkPdTZ18a/uWGcncfSlrqkT7D9xN1MNCb+OStcGuU09umRd34mKXOOYNjlxJjTet6PqdEzn2Ux7sGtZTFPgp581GeX+tBXzCvUOWcYmu8ieSGPm3ewEDrQnc42BzOQwCPdlVaVaXTgYCVac1JQEK0hshDVR0Vww8EmbhJchSAjSTpRESzn+QJoov1y/p7/QP/Eqy46TwmymlJjamnDb8L/7d9oR1Mq3veIOPSImcL97DNbQlX07d55XuE2PKchBdrgHVmPQlILywiyAUHyVhxUA0b+RgCnDOA25WSZxoQ6AHXhx666BrpYL5B9F5LDQ9q/YfpL5N+fPS7G6n9c7l1ZJymILQTEVJgfQ5hUgWBa9JCMoHfVtQbJpvWWKuKnjPeOLCJ0+VbCoBjiMfnU1O7pAFeh+vRscezXH2HisiPQUbtYQN5NkoxxN7Iwh8VDNTCrJVdakPY1KznhpKlOdwv3Bt6yUjFpE/4npw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: database
