apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    t7keunut66sbr: AgCorJ+onH3/Qv2kczZ2qBYF2MQFmsISOJb9nOkHh3VNdIHubfjPDe00mJVRvYLMQNMrN3L88D6uFeIxfZg3+o2oo5Mr3V+lrQ1X6ezDaxvaT9Z1KOTgzBbIashfk4Q9mzBiQyMmUTkbpVaeDXlb7KCuR5e6+nol0CWNiA2hQDq5Ni3OV4BUTp4dCwxWclzNwywLfTuVPTPGlnQe6UgY/jJ2UsxWk9ZoKDS2iQq/C/LvFICaBYY5LtcYKmCEYU5dc88YZjNMRCEzKOx49p105NMkBWN6GTqd+DYYCpLiZPpQjIx+whCmErU2jL4EeAOd5ZyN5lSzCd5R7oaBQ7UvqZEEdQrxsrIv+CDbDWKg1YCDe7OMaPLpbHsYOlTre18OKYQXGmhlJg88qzmN8JC93eHrDgICv8jrPkpWyJWdpoaj86ozzv8dUrrGC5r9ICeFFK3P3JSq/jcCZNIqmHMWPE8gGiGr04hDRSnnxYCRByP0KfzW/HbCgWb0mhV4eCkeuJBEsBWw7K8wrMxYbj3clRVM5jpI/G+jk6Omf7fdifvOyScNd6k9vpA10Ndg3lalixh0A8UjWpJoyCT/8/5XLR4DjxPt4TRPSu3U4pS9TSk2Q6xo92+GNd7ne7IB9tO5fGPGxZypdgIOJ9C+QxMyL+6utGTbShM+PKQ3P2aGj7tIk6O2djp+MgIzQKNnqkb+JLQ=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system

