apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-password: AgBNHSKDTD/O2GbLu7oGy2iAwhqSkY1AnRinaJWF7aMAdJgT8F5wqNP45U+k+0oLq+aB2C2QzVR2ruyDiplAWGLREZYShqHWPEtKI1eU7rOj9Rbdzd036SPaUpIqYPWeNdyIW8jJvVMnA79XdEQzejrhrhEP3xajWZCxzvo+hTEzDDYbGU14bpAjJgjVgdUVEAiFFyNdojpGVuD3vKUA10JvgI+/mDp5Zkfc4PEeq89uY1TbjbEV/sp3zpQSO2G+OE6K3asgTP3RKZwUS54ybYb3Q/HGzSBFigopIG22iW06asowioevcNJNeCe/kxY8XYUylry7YxT0cUKsZM2dkj6S3iV1dzDjiCk+8queDQlfMmJrMVkjEmy2EKuqNF3eeMNeqk6pP/fQlKJynu5J/LKprUOCwRxUgb0Oc6DNUWY8u0BcRZZ4gJgtu+WRFGUqsl7V4qUDUC62XL1LxGMchTJnOVV+bckrpoZkcGA2ShVPoFNjJSViD+XdTvX+IK9NY+b+81bSifMOwzjFE620evLNWYp7z2C4IeeSE1veItXooMuCyueNbtoeq1Aq79LzfOoo8Aj3BRh3Df5ycz11cPBWrZ9rl7khyT0RVCsQuQ4nTDqfIQXHDChZ4tfBgt3xR8V+0P554SM/4sMsFjcv5GiEKpwEd/MMtjuuXFcHSsur9zC/yDjmnUFeH9xxydvMuc45iG8AC/bBlGRtoRkOCA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system

