apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: flux-system
spec:
  encryptedData:
    redis-secret-password: AgCWu4TeRyhKn2REQDnKLyeqVAH3sjoWkUnDCQ6uNdjZpilQ7/qeebDJsi47lK4tuU2biCF8XBdOfrMC4/qGkgPxgHglxpozwhojq1pmLy7V9NZ/gNOj6KHnkFj+rWgvHQwhnMj1j6d+9MJvyLtBOZoiH5k2m7/DNgTdKK2CtVaGWE6mQhSyt4hBQYafheBL8QbE8joBq6ssu7mfR8xkbZ1VMJbkpo0SYa2T2JmiqSpQAcRh7eopaL1qd9lv7IZVVo6bbOqrHZmvpvHm87qysuiJy0qsPBveS6tyL21xZhidy2uWItWmP3XMzZGwfGpuc9d343ZeapEB164wSuKD2AFwhEXgLtMuW4qfGBTcNWQVY2qRQ0Yriz5PfQUYROiMxr3KeCo9aE8bIJLi/6Qg8N5vUVYpqPmj6p4oIXeRRW4QzENQPG7eDwTFq/FseMPFRyAtaGtlzoGQ4/JIisYLH3JefQr9hcgpdocIVzDYZ+/paWaCVcbx9GcyGypN1zlHu9IgErEBeDxcerYj4l/LKpIn1oULVIbMa+RK6sQ26q88RGTWp3BLCH3kM9CJ33D/MzEN6mEBcjuxWPQXKRH/oqCe6Pibl3FDomkW+VUvskjmTTtwEMYkfmUUF6EsJ0tclY36f9Cl2qJwBYVq7vnha5HmG7WrR85TO2IgA99UxOq3h8zAgvMLvLgtpWEgalXXTSuhJ5Ml+ugDWmIHdOwE0g==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: flux-system

