apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replicas
  namespace: flux-system
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc-replica
