apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: wireguard
spec:
  interval: 10m0s
  url: https://bryopsida.github.io/wireguard-chart
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
spec:
  interval: 1m0s
  chart:
    spec:
      chart: wireguard
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: wireguard
  valuesFrom:
  - kind: ConfigMap
    name: values
