apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
configMapGenerator:
  - name: values
    namespace: vpn
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - helm.yaml
