apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
spec:
  interval: 10m0s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 1m0s
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  valuesFrom:
  - kind: ConfigMap
    name: values
