apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: postgres
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: postgres
  valuesFrom:
    - kind: ConfigMap
      name: values
