---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: flux-system
spec:
  encryptedData:
    password: AgCYSvHpaG8V88Uy1II/UR6sg2ndss5xQZSDY4ffQSUWWNXoVSdP0KH6YleF8+GUXxUqIorQcXk3+X/PGO2rFYna9YM9LCvkymisrNyovsRpjm/hMpm87I+1nYoc6BdrsdI8CBJwuPQ3ZiT26wZBj1Qf3pQp3CRPRcIAsiZbkZzooJQ5A0W+8JJ1+83/Z1OduNe3hWLc+gPf33iquzLDM0T2Fw8Nkql6binq2WqNnpYGBLV8pE6JzAO0x7dofCbbfOPVm7Gm5G2PShXBlrLVnlAYkBJpdx0xcRiT/vE9xvuu99+QlNDCkg9yFcDwZE7jzAEATRSM11rKzAms9O0OV12X3A21oCIeb4KD9ejJEQig9XvHkBNNCyavAH3oTjDv07aA8znjMG1oEDWKP9d1djYk75jTUoNH0l9EzShSIg/hrai7aD4k0KvbwZVFE7ZdjX5LEcRx6mIev4ElWOpCJyg759FbHM2Sl+zmqr6GVfZcRd+RdKbZKJTk6ULhNJNMCpv1kRmNATJY++TNmltUut6O+/APQSO2QSMpEy9WxdGulbfO23rM6gW66b6HSh8x2hDiG/WMsYbP0LuVyypoJAl/cSenR85DdS05Topef8T4i825Y+40tlBGcjq1kfuTZwv+C8pz7UBNLBkrSmJM4EdiWs9sdZ1Xpd7c4//Fn7N+Vda34jD7e1yKFmS1dJpCYIsbPPUca6/1z54poA4V
    postgres-password: AgC3rjiDwX9epBVWQ9n3zOf9jSnNez7pmSxcB3ut2dtKajPOUqJdrTB0Tx114+p3Ylk83oJGqwSPxqnh4fRWWcTC6biZV+obYP2xULDz495dMgPXzeF6cur5OFYjayTLDEVUFybBKgfpOJFKioaptLyHsB1a7L/2bJwYA9nBI5qM0biT+hmfOHuFsBNn+VjZuqKIsKumlkoNY143v6sQq4/mgcJSb8AbBiEEKnDIZ3YjsH5BoyQm2w87giBohWndDL3E9oOaYpLC54hjElJj4pb8AfQ5mnkAgIuTXSSKJhfy3pVQLlhVRKvhk6Nwbh0Rimk0h5YjdlT9lXrnewYHC5ZFZO48PAubstWlrj1gs1d9va9DLXIllKEc272wFTzwhqs759sPOSAR9005ueVrx2IlG6oYb+Ke0tJF0gJmgTNL33+jPercLxObo3+V98o2szskm1NODyAQDPKb4PJ1hO13AzdEbGZS/ga7fNoX0p9/JHKUsS9JWKNwJRB2S3IGLavFho1TxaeuxnGhkaP2UjhblI94ME9nzkE0EkkYv6K0mxWM6mhslM+F7+GFp6raC133Xb35OUU1S9oFo9l8uG2JtCXYQCSl0akKyXmZFzzHw7BFx+HfHytiQTJ/t8BUwg/uGg5NmiIzvYYW2xnz3ihEt8hk0jhDJhmYPa+Swgy3vvgQZ+6OCzmSPRwDZOLBXtQ3RQME87N+DBWZgicW
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: flux-system
