---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    password: AgBeaICcAhzdHhkS1vihX51qXlzv2i4LGOUGLFjyJWrjBU40xfMOVM6lqveprHzI3D8IG3eTX5vbkqshaqh/tW7PQdE33gFU/70MGqpjt9PU63lnXtey4D2zHhyh8gbd24eft4UOg0UDqhulFAX2tYKe+PI+5+0JjEYNTgSPy5+koE7z2pumv6HZvR9T4H9HanLatWuYPBLCnaSAZZTK90BFBkJfnOx1pn7Bm5LkC7UN1tJnEPKVp4k+XGybQLwmXO2I0RX7viYTgM9Om/N+2qUJv+hoL7c1CF89PF2KRbAWyy0L0eCnLmyybz1bMrYAmqCgPFAM/XSasZu3RCeLnOFvC0sDfueiausc8K+PR+Qn1HhRhKWJJsqqvMot3FC/KaFvj3TM03ICA2s8Uppww2EbPXMc1iMUHapr4+PLC4gS+mvLKXgvGU/WKXXwO3Kc6WrANImjLt9Buxz4f84iha0p7dwgX9M5wNeP+8nyzRO6wNSCdIYHZOnKkSMsj2dhKedC6+q9LJz9na9LOmT0ghXq2nZtqN4S4LIQJ5FxZvshJlM0jxt+xbkwDcetVYMux8ydhh2up5peDbj7+aMFgtnmCFsmJv0nKSip30xZdJZ3ilxpCAgtM0zP5roi2b1aG1Gft7wRVT9y/8MjqR4hvPuEkkj24z8eQLdyRk9Yl0NwBPkKznsAUliEqrXhi0uq7a7CemZVeZfetzVld/9p
    postgres-password: AgBD9nHvHVtaxS7TfUFiV1iQ4Sd8qqVq1VHRlx+nOyI8sC213P7xajtE3TCl0d6KQzjl9Hw9KlCHF9EEnsQQfQqa8EzdUYYCyMopK8KcLtb/YsX5P6BiKpAZ7NhJM+RJ7gddfoEuRyZ5+HlnH4vAlw6ipo4jz/GtsRlWyfJVL2A6awWxyKLA6ZcFTiC1T8IIaMsOnerIs+p/T5Hnz6JN+m4lqzdiFa5o+5+tmL0755cG05o3X5G5U7+UArp3ol0dyHeamnmWV/WXRGV96sm/4XvsOHejK+GBnrQgM010GcdS4WoFUn97i28xtIxS71gCdk9UxmvCtReqvVSbv1yzjrbH7uzBbDBWZ4pXnMmHRUZeONhTw1ZWmInTKPriBEowvcbqt4LjtWClmFV+4MvxpH9o0wbco/MS2S/VSLRSp5acn65VesymaBxpp9/g19tJchGFgkZLikvxrgiK0rjD0ldj16ytL0UEPCAAjIJmyg835BKtT6KKAljcP735IsMedlMqyVhOrsrJQfo3Wk4Qe54NeYPwptBCTk9nrULvLKLJB2njV9O/Vl62rdhjbXbmwxlMXFXBM6BmH35g+aSZGKgQMbLPRNLjEKE2DJZ6XpUFncLQjRxswpEo6BpU1stqWZXBcNhIifGH63oGU6+l+42iqbrNlNx0SAhjAUPFOK/nnpNiQlaI5crJa7mjcZ9BTkQa1AJunWLjSnJDNSgr
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: database
