apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: flux-system
spec:
  encryptedData:
    password: AgAJqn31JZd+quwEnOIQVQiCvK6P1tHjKt2kByTgU2Teptl/YVoN1D8MEzjJo6IorQw1IDPVwislKeTG7MzeOx5kjf4xUl12f49vn+HqWTRJL2jGbZfsxYMc8eejICTJdtFi1H3o6F+lqnv4lhiETyBWArzPIRgBfh6FP1iNPcKSrSiEz2D8pToc6IvDTp5fwigKkr1mVT6MQ53Zh2gfflmc4ajqfvb5uvB01b5FX25434Hth17WmuTavNMxW4ZJUM4x8CHWpzltJOvYVKptDPNifSOFi0v88mIhwqEYHBhXD52n0b+NU4Wy6p07wS7Leg7cwLT/zkWmzkKsrhbv0H5kCeDeufmK1Oc9+/EP2MsjrM43nRMRCzJdCr/WnxYedYd4w9U6yO0kSP5WK9SHT+6p/hmM2tgEAudnqp1BmSKJj2739Lw4tiecNJeBzkjYgnGmQFZ4bQrU/t+HDBvjZYDDo7HSqKEjrn9kozjG2OAgHj/x+4I4IRI7ELG3ESK1wX2KbyrTz3NQtfKVnj0snM8wXM4WmdNjN3/d6eLVWRSJeuxLd5O4kXYU4VNc15U5Z3DCZZfiLEeYE+K0UlATSbxGfR4xfZm0M20YQ4IyU/KhPMWlf+jeVeeay4nqUF4ZwdXy4bSz3oKesRzQ//PcrdwCz7WCHs25ABB82qlEKlfpqcsWirufq3wQfh9qSgsdJNwbh5X16AYQW54g22l3
    postgres-password: AgDLu1zaFkRczwtida43ZnYehgCFguBu6y7JVPCUjCpJQIJi0LIF+T/jk+gCN2lfJDysQ2u4lKyCZifqgsn13VE0SqE9JXhoCrfCjXpAbyvKXDmmyDW4gYC+wIic9d8hTBc/D6KCDwrJOjkgRxgUGxp7ExzizY1xyzbQ1h9ijvQXEe17JoG7BIN+U/1j5xaUcx6u1QuASXyvy7ZUhFCQmfmvrhLwaRfprvVQMhPCrGg4vTXHIRhuCCoEDHriFc2EiV0eLV5eBNUnUwh8CTDRyYOUUuhMc8JAbtIuqfYgFDlzCpWUSu8ZGlw/Y00HTf2PYk6jlLwp926RgPzhp6PIvWkl/jU/pmIQ+zyeoW06KUA69wSSr0EgJjvO+LrqUZNwbGJFE9xZLnrSvnt/EvRhmJGUmoM511So2q/m9ssJwTuvlRyJe3mKRJe+EDHEvKyqu3mPl/PFlLYnHWsJaa2i2O16nf3d9TcGC8hK0isWWXZa+P3OQoAo6KD/KMEB8Vm4UXfmgQsdkXjPA/DksZ/0ckhtHnmPQ8RAZ6zVQqd3AeWHqEv+NM/FsN2g6R74cvmlckPuTHPJU6dr1rk1D6FXT6gTRnidho5/xOBVG5uQqM8qq/umW3YtGPj97qrgxvC0GWq2CWOi4nIcfgCERLdhY2CEi/hDkBxkSn59AgPSK3DTuPsLEZUQ3MeDp7BPxdZKJvenDk2MDQqlJTkG9f1y
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: flux-system

