---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    password: AgBY2WxLG400WtZg8vUAlmP0JrORbtRRYURRob5vRrItkpyIUfqNmnBZofJQckNa4/qEezMJPGoAMB3kmf87u4ni6CgOotSb4Rvkir9JtYBHFa367W8q0jsani2IFiDDIWVnpd6EvR4gg0itqD8q2C/3HBzviPDGWESFL5vKv1ShwOzjC+P7AsGtsbyiqavxpvy8hUVrb6ot9Mqwah3K8EmFjYOSYfj1csq5VhRb+zBD0yP1PuVcNPP4WifGaTLKnMC0GSp3L8ZXAszG6oxskqI8cr5nEZE95sUbo0XrQJy9i5Nv8UpYjD1wXe3cfxdKV4S8yjsXnIAWPVkS3zqXkxQyv0Gx9jOmuqVQ2fWup8ECmC17yJ+M9N+3z64thzLZfqlzDA3IZDNYIuuhWNdLkyw+DrZksw+xU9nlfwb9KNFvHgiBg3BPehYFjTiXbpcnISzLKqKNSnMvUu0to7V7q1tmSdXwStnKD8V/EljKySczNcWpZ62kkC4B4Mqlo995SZpcemDtNTRi73tzWrRlHT2ZJdWjvr5ubvtmFJNtAb3XReZ0Y0j+OaUfUfzOqtDcvGgeYALGSF1o0eJyLnP5i0Do8rkU+arnw+8JxLzNbiRbzaqVIvzvlS6Rd4ufhkCVuGYybtBNoSeoI0xr2ybVaLgISsXE0W/ozUrI2nTNSqDQlY3fZWwYwxvGXhvqz/xpA2YdqQTUyvH8h/Qd3qmy
    postgres-password: AgAxBAN2STk4bdhSHxfPtfl7Z0haL1XIlobWadmIPtAUAyOdiKtztYKcAUZxUw6wVe1Uw6FxHtckm43OmTPSnwxwSUjOh9g7B5EHzKxQf4VDfHaJVvUpoby3I10kqGI+vR8P1ePEs0hG9oXJjfbHtTkBJOi3NMyA1LltEHhc3zWAf/wV4LFAuDe+eNmWVN+rqwkl8lT8IaMv02Hh+42EQRYda+ItaiO8nEtYEJeY3DZ6+NxoZ0mJsOSlxysUv8pqKr+RIDoRzac1PLj4M/uYNy/7tplxsaZHQCysnFl6KNHfFf9pSW8lKPwhRNE8rGPg1PIL2WFMAKWjDLiEbLlfpRVQVCF2RSPU6Ol9jOvqv5RZn8dmZbSM3pqUdNJZ8Xr+dn3p7ZRQ18yGFWGZa1gyQfzcoOFqmHlUpKxXAmMuLryTKc1apUngaJZxXvALl/dpmHWpgcdzPp2FozZeLHHIzYGrAIzX+n7HKKIHsCSS2QYaMrm7UNPj2WTvrQ3KI4v4xtonwMBGwsb5u3AiTVJnGD/Ekb3UuNTj+oEsyjN9FxkqBEDOBfViCorRwa3CT8C7LseZyc7yz46qxVUaUbuLJx0mgq/zMiL18r683ARPm1hP1H8iSXwrng567Hh+HwVsuE2MCfxq0BU9y1q/waOv3Dhx+10h9OIiouNv2S79/yTAsawB29vp9k6lEa9l4hJgr53iKKR85s/0pzv3O3TS
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: database
