---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    adminPasswordKey: AgBBzj9nDbZo3MN2a+YaoV61ETfUnqH4IBOvNmL5BlltVKPqqOmpxwTgtqvn/6EByn00bSLk/9OIHZ+BAjqA4I0+012RWUuDhMnInUD8ajE1yhmEDmlZIPCwwLl4+652yf9rPJ2ATkx4qdMmDQdISmmmf0TWNBdaYd9YCaKvLtNlDThZFgVYu1VwBw7reoRG4TpOkSil+vqr3x/LC3rRRDVg0IG3wH7Z0oXncoV8mMlvngOj/WHK1XQdwGcnbBC0UGu+vBH45WZUnmDLMjF0g9L8XkqmC1ksUZOSWfrnRQsRCc9VoEEwBYtAVtP+x1fU8TE79ipqWrUwi1MIZE0/wtUzt4dIqRIF78Y2ffvF+TjQb7iMNljEtbCv+d9/oQWoDXWxhEhd2BnqsJDyLRv09DJ8bDwUjwLl8NkQ95exWJW/yKZMuZCWgYMXrhCZxIEVNwDvJwvYhGrW1QbRYoT8CdeOY0puGntsq7FgT2DVFaNPReOJdzXXToni1MXx7OUqDM8qb0jxXxnoV3JHaRbCqE29cDfVGQUAfLS15Pc6Qol4kT4BVF5TxsX1/VefvWt+bUarevK1V9rlhJTcKEHZb7wjZz262IE4XMsktb+z9/QY66xX+80SgIi4dO+DHpvnAhqxmvih/fGG2JtljZdthS2zUF/wfzkswzr/Ls6TSYvbX+T0oSoSvN58+PsmhBctlDAg1JkGr/FyVqlLaK4i
    userPasswrodKey: AgAq3BUNn/cxo9p7rxID/md29nIgcgi+Uxy9QhTcy5+uLYDZMoNFt1tVf3RP9y2eGPZYCvJeUnkLDdIIl8+TQ0Tt9eeshwi1jMz4guGuuhhI1Z6lc3jazW+IncepMbSxCP3Y6QIZamVTUo9ukRKbmippMViCKuykmZ5DTsUaQhB6pCbZ7psDjtIftV/TYBTFDmpe/kvKpSfODkNeFzHodiyDgAb2QXF+FTxuXn8pG72YTUKd5+phmTM/6ABvBO+s4EVJlnmUx95DPvBBBIWkKU7Ev2T8MbUcdyK2vFqLpcJVWfx0vbD2hR/bSAvUudoLriEVLftLx2X6fD1nYs/SAniKVZPwe98L7CDoSiyNRS1c1wRHRkRqXAucvKucbKlW/TzV5/JT+qi1NpMI4Y68sA33jYbTbr1e8UfDr1Rx/yAD+xv+qmMMn0jrJFVf4z7vpK2pAtLL6oaMMCLhGmv9myg8hZjL3UuAlmXPx4apgUCK3FJ303kYzET4ie6mc2PVT2YTuYWr25bDBqwLYZuQp/d9S6UvKK01G+AgMxQXB6qfdfOL0TkhNsGL5cltLnSPbsRvhpSVD2YvPidejTkZwQzH99vgNexoRDeVbaVtkevQKz5HuwjIb1wHDo17YPetwtYFDeB08gsYX/dopolO+jkjSfPjw9pqSQSx5WZ+Vq9elp5AWQ6VYv5bKUFHdwd1YKcoq7GNoKdwpIXzwLQy
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: database
