apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: flux-system
spec:
  encryptedData:
    password: AgDK9sLdUlwpsw0g2pVuyHPLu71Jz0VQeWrbOuqzrpu9AHRBx152MA+L0cd28Du5IH8bwVyKzYQaB8Jn3cJkqaHfM2jAUPA7F+VUX6hT5OU57lO5mkcVbKnf3+nVBeTWApN/ogBQdFppz7C9RYOaeNQy2Hh3E/OMC+sUVyYy08fubTCqmrT1VugjeXIRCUryPKLG2dgDlkFyKMiJsvdymF8w8iVfxohjy5RnZ1XenQQlWUIXQ8YdxPISHzVAKTkTAQeE6vXVzAzl+iGB/jtjQlbD8i99E4siSIy70EuL6+FEW+zZdzHy9rQUOmVn+6zpaXKmufdXMdwlYQW4G/Jjd8iHxitmav0iKAHin0i20e9VoeXLrV55noEvL4DM49IY9waHqZLBjg37Z6uHx0/WyRV+sDga0bTZdG9lw4G61yo5vS5W436Ss3a1/+nvxZJ98wc2g5LI3ztBXgP1cfkXxkt3iRkBLwHOop8C9B/zGAzOxDBjFAlJ/0MDStE2qQhl2SF1/c0Ru/rQKuNlKU8WYy0cHAxkT+kDgm+tqdZPpYVHP0Onk8bI3wn/GMq7+cOz8Z/JqvlQ6MGV55pFt8VFn/VXMZmOmMx6wZenz1sNEbsQTraS5yPtP16OaN5fAxnOGtny22KM4X1YfmIgOhu7FlyZv+rHL6Eseh0D1etBQczTPeQSp6z1s82c3OouL05K5Alf10oPAWgWWa/slI8b
    postgres-password: AgCdPncEtdvBCNJ8fareWEDDAk61FeIieOswKrKMekHsSJ7S/ch1O0GH7bEO2LBnxcCWmN8yrY0kBPtTyuaDqTEn4u7ltikyJrui51+UrOSwNaYc2pIKh3zoabYRW1wI23El0MhpWu2Zq57jmEtPqBjKqseJQTEfHQWzDp/eWi6YF4lUsv2UkGw8YKCwiY0XnWVFRS5RlDxKTKoEpSS9GngbyRLeRIjBIDsEcuOcOwNHbni5aLZBVwRPdlryc3L0yLLZipSndJd46AlR60CUACBKvYj6W5gmjxn7QfYd1M2ZPQQWd3mqbeQcg0m0omylE6SzStItMW8ne1fBoitnXyRS1OT/l6EAgYvGlpEBLbEbBZB9zaCJkHqUQpyuzPSl/kbfNsTQnGeC3Q5472GYncAVscSg7c8VcGXg34EVp/ZVMiFUerYglHVw+W1+ssDO8+lPe2Smd2BEpPGMi37PkxpuChdGFxfXM7GfEXqHvT6mkoiZzZ97gAKdQsCZlLjz88ET+wLVPKxnQtsjcewCtLMs7rzt/lEDcIZPW0zN5g5dn2yPrBq3CxgCJ38ebdx+WXiv5TiDr4ctfMaFqYQrPvRasKLgz3EH15NIFTRVC9LZteDJcX6YsXf5YXb7ryKAvJzQNUyLJN9ysM0dpOYf5RiM0+wijoZPiBC5EY2lD4wBgMFWEIZLiVumsCWgLDokSZd8BwEf6YoCVoX2ucV+
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: flux-system

