apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: flux-system
spec:
  encryptedData:
    secrets-values: AgCYcRgKqZ8ifIcb8dHrbIdcfL3cd2b1EBtmlLog9IqbrI9rx/cvDxDytLULZ1PICVBAZHkIgx2KlJbODQkV7Rgc8nnoSUPDYBUjT6oZODbx5LBC9Qnin0UwCduqwcAZbjcN+YilkxSB7JOjjG/H05qPVnnkKDcBb0O/2TawsSSUEnwyHN8VXlJr3GOklvd7bp3El0k18J5khwfTqA/fZKdCbPpoESByt6E8F+ishTDDterxxj4WYaPT28qiIfIDTg3pir0eCJ55rI6PLGpO7p1zOzzBVnCoVKKM5z3cwWR9ogXqPMR2h0mhtW0VMIuixqU/PN6lc1NlsYJBlGdbypKt4F8RyS1G2iroGJKwOBFcfo2FcJZVgzUO2N4moLZFTYCD0itFPE+EY5WmXv3CwsUHrxHwrDSXNKl9DCeOfsnPqxNaarlelbSBr4qD6lNIrTQm7omuA8Wv/faFQtauXomw2S49o4HONtR2GXAEtnfWacUaWdUd6HBGSSlxmwMzz0Yh1M93cVylPeG2ABkmqI2I9ou4NM0ZH3NcvWYq0/dk0rYTG1+T7Xsp7SiGVBy7W++4Zgtbmc2d93NCFIDU8drRKVynul3oyB/P1WOsHZRc3bh43zIipYjPT6Ahh7e/qpiozWBWDGmBYLOx1IqkZfn4SfkDNCKuOqxrzPE/of2FIqeADeE3nylJ+0wKxX8wqivOoE6n9nEEqyMNR7VpdwITvPigZjdO3S0e7BJch+r8DGlAUZdBilzagCMfsDWMPlTIfMtzqJ5QbWw=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: flux-system

