auth:
  username: "segre"
  database: "postgres"
  existingSecres: "postgres-secret"
  secretKeys:
    adminPasswordKey: admin-password
    userPasswrodKey: user-password
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.0.0-debian-11-r13
primary:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  persistence:
    enabled: true
    existingClaim: "postgres-pvc"
  
