auth:
  username: "segre"
  database: "postgres"
  existingSecres: "postgres-secret"
  secretKeys:
    adminPasswordKey: admin-password
    userPasswrodKey: user-password
primary:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  persistence:
    enabled: true
    existingClaim: "postgres-pvc"
