auth:
  username: "segre"
  existingSecret: "postgres-secret"
  database: "netbox"
  secretKeys:
    adminPasswordKey: password
    userPasswrodKey: postgres-password
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.0.0-debian-11-r13
  debug: true
primary:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  persistence:
    enabled: true
    existingClaim: "postgres-pvc"
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.20.202
  livenessProbe: 
    enabled: false
  readinessProbe:
    enabled: false
