---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install zsh
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
  when: "'zsh' not in ansible_facts.packages"

- name: Install zplug
  shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
  when: "'zplug' not in ansible_facts.packages"

- name: make .zshrc
  template:
    src: dot.zshrc.j2
    dest: "~/.zshrc"
  
- name: make manjaro-zsh-config
  copy:
    src: manjaro-zsh-config
    dest: "~/.manjaro-zsh-config"

- name: make manjaro-zsh-prompt
  copy:
    src: manjaro-zsh-prompt
    dest: "~/.manjaro-zsh-prompt"

- name: make .p10k.zsh
  copy:
    src: .p10k.zsh
    dest: "~/.p10k.zsh"
  
- name: set zsh as default shell
  shell: "chsh -s /usr/bin/zsh"


