---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install zsh
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
  when: "'zsh' not in ansible_facts.packages"

- name: Check zshrc exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/.zshrc"
  register: zshrc_file

- name: Check p10k exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/.p10k.zsh"
  register: p10k_file

- name: Install zplug via yay
  kewlfft.aur.aur:
    use: yay
    name: zplug
    state: present
  become: yes
  become_user: aur_builder

- name: get zplug via GitHub
  ansible.builtin.git:
    repo: https://github.com/zplug/zplug
    dest: "{{ home_dir }}/.zplug"
    force: yes

- name: make .zshrc
  template:
    src: dot.zshrc.j2
    dest: "{{ home_dir }}/.zshrc"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: yes

- name: make z.sh
  copy:
    src: z.sh
    dest: "{{ home_dir }}/z.sh"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: yes

- name: make .p10k.zsh
  file:
    path: "{{ home_dir }}/.p10k.zsh"
    state: touch
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: not p10k_file.stat.exists
  
- name: set zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh



