---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install zsh
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
  when: "'zsh' not in ansible_facts.packages"

- name: Check file exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/.zshrc"
  register: zshrc_file

#- name: Install zplug
#  shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
#  when: not zshrc_file.stat.exists

- name: make .zshrc
  template:
    src: dot.zshrc.j2
    dest: "{{ home_dir }}/.zshrc"
    force: yes
  
- name: make manjaro-zsh-config
  copy:
    src: manjaro-zsh-config
    dest: "{{ home_dir }}/.manjaro-zsh-config"
    force: yes

- name: make manjaro-zsh-prompt
  copy:
    src: manjaro-zsh-prompt
    dest: "{{ home_dir }}/.manjaro-zsh-prompt"
    force: yes

- name: make .p10k.zsh
  copy:
    src: .p10k.zsh
    dest: "{{ home_dir }}/.p10k.zsh"
    force: yes

- name: make z.sh
  copy:
    src: z.sh
    dest: "{{ home_dir }}/z.sh"
    force: yes

- name: make zsh-autosuggestions directory if not exists
  file:
    path: /usr/share/zsh/plugins/zsh-autosuggestions
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
  
- name: make zsh-history-substring-search directory if not exists
  file:
    path: /usr/share/zsh/plugins/zsh-history-substring-search
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
  
- name: make zsh-syntax-highlighting directory if not exists
  file:
    path: /usr/share/zsh/plugins/zsh-syntax-highlighting
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
  
- name: make zsh-autosuggestions.zsh
  copy:
    src: zsh-autosuggestions.zsh
    dest: /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    force: yes

- name: make zsh-history-substring-search.zsh
  copy:
    src: zsh-history-substring-search.zsh
    dest: /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
    force: yes

- name: make zsh-syntax-highlighting.zsh
  copy:
    src: zsh-syntax-highlighting.zsh
    dest: /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    force: yes
  
- name: make p10k-portable.zsh
  copy:
    src: p10k-portable.zsh
    dest: /usr/share/zsh/p10k-portable.zsh
    force: yes

- name: set zsh as default shell
  become: yes
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh



