---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install zsh
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
  when: "'zsh' not in ansible_facts.packages"

- name: Check file exists
  ansible.builtin.stat:
    path: "{{ home_dir }}/.zshrc"
  register: zshrc_file

#- name: Install zplug
#  shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
#  when: not zshrc_file.stat.exists

- name: make .zshrc
  template:
    src: dot.zshrc.j2
    dest: "{{ home_dir }}/.zshrc"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: yes

- name: make z.sh
  copy:
    src: z.sh
    dest: "{{ home_dir }}/z.sh"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: yes
  
- name: set zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh



