---
apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: metallb
  namespace: flux-system
spec:
  addresses:
  - 192.168.220.64-192.168.220.67
  autoAssign: true
---
apiVersion: metallb.io/v1beta2
kind: L2Advertisement
metadata:
  name: metallb
  namespace: flux-system
