---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: flux-system
spec:
  addresses:
  - 192.168.220.64-192.168.220.67
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: flux-system
spec:
  ipAddressPools:
  - default
