controller:
  watchIngressWithoutClass: true
  service:
    enableHttp: false
    enableHttps: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: marokiki.net.
    loadBalancerIP: 192.168.20.201
    ports:
      https: 443
    targetPorts:
      https: https
    type: LoadBalancer
