controller:
  watchIngressWithoutClass: true
  service:
    enableHttp: true
    enableHttps: true
    loadBalancerIP: 192.168.20.201
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    type: LoadBalancer
