apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: flux-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'segre@marokiki.net'
    privateKeySecretRef:
      name: acme-client-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
