apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-lets-encrypt
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCsA8EKzog3W9siiATfTMC7jaiWwODHPNn+5MvpyW22Z83ePFBQu7tkKe7u9ReqtvqtnhJt+sIYGYIhastF+I1qGflB0rttB/R+jnjbhEGFQSZF26fx+ta7eysgmQLKc+LVfdfhV+aTaLUJSgIOhgud4bQCGzOkeDC0+RbX7/TFloljg6JcnBnqeJAg6n3DCSdhJ3akQIS7EzUHcaTOLNNsfbbIwmSreq4009IwkFznTZGYc7b4N0Xo+aZG94Mt/enIxVVtoPVEFolGObissnaprbgqyO+FC0h61dUN7tUOgMUDTY+QnkOc27k0/lWkzxhlHESxMVGyNK57A3CwhbzAHikDSqLUSvCW8mUnSfjc2PHxI8532KRZ+4+VUz+d/xU/1sRilWnFI/SQmRzPXF014uEtoB9gRZWpESTxycdWMWjw97B+Zw+Z9GTl5q0bzju93DEgsh6DXzQQX4w/6dyaCW1xOFFi0pK63KD6Sjz8IrMNUENWAUA2qwvKyCa1rfDVpXvKWXOf7yUzU5iCA5jnailC3sCcgWVRx0xVLlkhi8XunXctKoQ4MYbbScWV5V9nYqcdMnxIEi4Mwit5QqhKlcyYkWhxALwiDRqskpdcFKbFomQI6nFVKzvTdAgz1Uiz4osQar4yUQ4DhqcG+zyj5I67p2cBg0xkIyQiYWjcVvyJTlKmvCiWgo5V5D4q5wiJYYBb6Lg77FDToKCzGypDZV2HcOC/Va/ooqMPMltYn98hRGTD2IFX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-lets-encrypt
      namespace: cert-manager

