apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: le4db
  namespace: le4-db
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: le4db
    meta.helm.sh/release-namespace: le4-db
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: cloudflare-lets-encrypt-le4db
      hosts:
        - le4db.marokiki.net
  rules:
  - host: le4db.marokiki.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: le4db-service
            port:
              number: 80
