---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# - name: Create Symblic link
#   file:
#     src: "/run/systemd/resolve/stub-resolv.conf"
#     dest: "/etc/resolv.conf"
#     state: link
#   become: true
#   when: ansible_distribution == 'Archlinux'

- name: Make resolve file
  template:
    src: dot.resolve.j2
    dest: "/etc/systemd/resolved.conf"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start and Enable systemd-resolved
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - systemd-resolved
  become: true

- name: Restart systemd-resolved
  systemd:
    daemon_reload: yes
    name: systemd-resolved
    state: restarted
  become: true
