---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-external-dns
  namespace: flux-system
spec:
  encryptedData:
    api-token: AgBBSXLWghcGtFcPQyB6CmGogfHaN0o/RZJT/3R6sgvIkI/z8WHdVCijWg9fBDB7oei9g5eLBKxXkomht9jJQMeR+IuuZ5hodEl5JnwuQ6ta8W4pqjjSnyE0VGfauvXUx7riGprw81EvN0s2uV8tPX/kRH/HkekcLlwo4b5zt9CZl6RaUvm2FxqfEB4Ykkjp5MPT3Gm+6esfIaffotLPVMLzmXVedCCKWPR5TFLPZTlSwBHjG3wcHTjdLQ3dotKOyDRVLoLctJ3/Hw+DQmKG0W1BkognHs3F4JGLczUYFj7QapCppagSewX7VieHAdbx8VWbsbR8RChECqORTIydhvO6BLAlWOh91fknY19C+6p357PLY/hS3s7ATwbcgicMiPWEZKh+315Ao9hJec8hc7VdzNs8fqahwhbqUboMZZf7wKnZYrYB3toCNTz8E2CRIE3JXrSoIDzKtVZ+MudVot1beKzBJXrlbWwwKyYK6iLau4hm1OOgGRWBP280VQzby9N6rwiAVz5ZBrJaAuYEkuMhXeMyOq+gP6XIkHWGw4clYp+3wapyRvQBRP41ravDD77nqDBD/XSs0vx94lWgQ/aixx2T3JAsrsIIhOB6UwO5gq3Ht9iqs7hlHd0f8sKFt923diXlPnOafapAiUDR+FAGbm3cFZkGX/6yAlWqZL5RXheLlThE9SOsijcj79oC+pmVOCovA679DoXLKbdbkVBa8Bc9Dy2qJ8DcE9cC6uWEpETMJu9OqVx/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-external-dns
      namespace: flux-system
