serviceAccount:
  create: true
sources:
  - ingress
  - service
policy: sync
registry: txt
txtOwnerId: segre
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-external-dns
        key: api-token
