apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ipv6-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ipv6-webhook
  template:
    metadata:
      labels:
        app: k8s-ipv6-webhook
    spec:
      containers:
      - name: k8s-ipv6-webhook
        image: ghcr.io/segre5458/k8s-ipv6-webhook/webhook:latest
