---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install nginx for Ubuntu
  ansible.builtin.apt:
    name: nginx
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install nginx for archlinux
  ansible.builtin.pacman:
    name: nginx
    state: present
  become: true
  when: ansible_distribution == 'Archlinux'

- name: Copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
    force: yes
    become: true

- name: Copy nginx default configuration file
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
    owner: root
    group: root
    force: yes
    become: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
  become: true

