---
# Installation
- import_tasks: apt.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']
- import_tasks: pacman.yml
  when: ansible_distribution == 'Archlinux'

- name: make vimrc
  template:
    src: dot.vimrc.j2
    dest: "{{ home_dir }}/.vimrc"
    force: yes
    
- name: make vim directory for undo
  file:
    path: "{{ home_dir }}/.vim/undo"
    state: directory
