---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: flux-system
spec:
  encryptedData:
    admin-password: AgBx+iwnwelaSx8EQDLLWsaEv1arl8VZGK+flVXitIYWrZ7zN+h3otwDCmqsWV2DWquGgA1/z0D+Y4BnWHdXzkvtMIykGvLFbsqXU+aM0YOo31xQqjWAsNs1YWGivxq9QVtwba4tH9l53up3548h0RcflZUsb0/MAlde/5vwkdBjRVn+GaoG76DqyjEH+i0oZFr3fJFth9BV6N1bqsqInFu1gzb1BR5t++WvYX3Km4clzfRiBpyIpox9qCpxtuZtdq9Gm2isQ3ugMZww6qx3vl4F8DloY7HEif5BtyxR19fHExIdM3QS4+pSqtkPr5aajuN5AqOpfHZFdFuGpD82JBogpFrt/CgfOEGa5xCiOPUuRCnTSHfz2zGSgX/MTpv/g3Idkwjkn8CDQv5DX/zXtjlSLg5eh91yfDTkrpybKzhmixGNKUqluppwhMO8f8riOBde7dFmpZNSDT1tLzBMkVCBAjpV4hLcBJUzTgOdLh62DaGFcDJYEyaAoZyaMe8gcjE/OYjpcjzPlpp3cVJEXMVQfeP/EF+tQVWIsxXT4BPeY6xkTLidxeuz3aO1+BkcnpMbNcjDqhrrDZ+7bLSZiL2SWRatuYEKxO4AaeqHWdC+tRW7M2jYld/drKQOIOLAl5g0AXk87D0/E/82bt1dnV9btTcTBok5y/HTvGpJTeJyWwfoKPrbUhGNVsRVBVHtEJnDGEngIBqgGeB/NTDbF/BthuB3feFi2q7Xtg==
    admin-user: AgDdVnTr9fa+H9KdGMddpPXYtyxw8iYBtvR4X6KQXcO4FTjaPZfDGC5n6p7oPMQQvMJo/w0Lz/6KUpfeuG339obcQphsVfAaSrNbHbsibgd4XrdTUb0y4AWXdujPOi/DDAQeGaTGUglpPGlxGDb57K2CvhK1nLuNA1lwkdS+fcHfECOPeScDc+wZfMUO1rZJ28hDDc+PmM72LkE2bHQFDN9j7YwmrempTzlek78gX4QMpOBkRoTqc6FOzdN5Dq8akVdAc3Ry5+Il2jA+fCpT2/uMChtl+6pgic9i9SKJ/bBMDLMPFNhSXITyn0jBcfFfCZ696XCKinxFzUDZn28Ls0kCIcCLu+FpRVI6LF9zS8A5kRmAReFQgqrhQIsE3qdD3Q7eYoH13b3+uWIDyqhL8Jjk2NuislRbhGQgv6QWg4oH4Uvr7NAQmX9u0NMa52aMOYX3tMsPKHHBUzzRxymLxWXMR1Haphb86nqaPDNXqk8j/RD98CFj8LoHODhhDgdl5uN8JRbJNECuh43tgc8h+GSeh1NZXfBIgHFwBCgMvXWo4yr+0lD7tYxt7nTqJWf8+0vYKZRZocmT5kToMtsJwql/U8TmseJ0Oz7vkC6NsuKRPiyZhhXCly6qPsfbbiJz025N49WWflxpp8ZRuIq73ZqRN+HZpW38KZApqNxKpYvtg79q6eT42tXjK4a6T7tpIqubngZ/ig==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: flux-system
