---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAR1efgA5SABIrbGRKWqsg9qtzc6I3iaNOxspDnVlnnM6FsG+vpzMEjC6cosrx0EgQd0NyYhC3kYeVv6pHX4uExged12i+mc2QMmecIur6C2uNwWSycVGwmgosFzN9xKZYBJR6V21fqyuN6HLV4+fjMejEEIrANdGDWtfBsglvZ3AVKMj+oi0v/+Rs/Dma7zjn1bFH7zd4DmgpU7JDD8lqXArzsaDMEN0w/CIOUG7dZXpWDrP3Lc0DOYZpYotYSIFf7DoLnIXDPggW6lDyTQJoeNdjqG/QfWCPVc1+xtF5+ACA0av+/kjA8Y+/te4FoLdBsA9HYdL+yJLbhB9OYJBYvgS2Q20l5131RnhZ8/FF1qorocOkLOkM7xoKwh0CdZS9jGp72UyX7mF89t3/sq+MGeFlce9b5MOOiIX3udIvKY/owB0KUa61T0Y5bIqtPujtl9zIYdrykNGIplyd8oy4fIUIjSenJsF+uGxmlQRLCxdUg5EL/48qtTDzEvx7CCR1rP7+pz6dvAI3PovCelhHfIyECK9220HQa+shCQdxRWCryhNCXYbVldg3z8EhB4raPJJR1awI9v+GY0axtaA1x1BJ7Euew4rwcV9O9tMxgwKMsu3mfqs+PsjLhxz3Cs/LeSqmwU8djWuuuN+/02Hpv5DQrOGxfT1mzIR824rzdwSOl5X8U4CiWNVkoHIbFszAlziTd0J9LKNerXmD2fcNwzdPPnxjYhpF+JA==
    admin-user: AgAd5J8+bPopr/rHAVU6Xsc2CmTn9FdFp4MhUUPWhS2VwnDRbTEcbkjl91objvj1E7AxPQByTCTbunA686SdCM5MGYthxUCvVg6LFScOIvvWCpTNglhlqLBbsjvlcV4gMW78/35w1GeWdcY89Jp/xUgb/hnahaT5sHqm46EvoVwaO34a+gO72i5+xTa1MsWom+kwbdjaQSjnOkZ3f6SG8GWCIAS39ZLhNRti5vsnOmVvac/ADWSiyv68SBFojDko6A6i+n4R2DskJVrt0cxlH40McAZahbfIha/YK/QyK22vgKXLisLCoMcxSk6Kjn/YY2PtvlD/sMB2zeGPVlAavtGfLHMWv43FF10qX+acfQwZGYsLP40RPLWeWIJTrFmGsU+VzvDQj8SYQgaHFBGGWM681HWJ91n4TX3sUEHq1s4zkvUGa5Qx5xtL3lUilo4sqVcaNlx9TLYGo5cZqiqQw0zkUMPuy9JQ8ZrXubQwrOZXFRDzAWm5B8OHltKYLHu8ci7WlZU1SQkuZSTN/JbxnVWabN5UTBn0KmJrQl5GE/zXQ6ggLQmWTwI1NtdP7WnSubQ0EPFIpXZwcl2xD0F83mIuvGjoIXu85U96ohrNAUd2BhbRpv/abSBtAP42i7tRcHdVgMSLdj7hjZGr+QQuS0JhPW+02xutysTZZZhGLOqP6391HHadD+s19RsFpKNLTwDD/JoCOA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
