---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAuV6Rt2Zp+FybaQ5zfwu7udzytFKctJ/PYmlP76mVgfH3KEFDhjFeYeeijTp/sAvGy+z/gef/ghUvZQ0QbtIP7UXotGfVhgd9l0qnJP7X7W/QvmNbARV1fO9OToj72ybQPXlRum2egqt/LhR992s/zgoolQib7zyyN8AUNQDeKJZSj0M3J8eISP/78JWLpBHl6pGMWD0cG4kI2L8y1RXbpafD/iDJ6UuVH/LjXb94LrAQPSNsbxlcHl+jnSDgpQF//QZWLGCd0i9Oxt0yH5o+V5wwzMVk5Rn+AeaylQ++7fv8yMpvaasNASXbSMOFLDYnqB5VV7nFhinUm2WSFM8flKV2JYoIikcNb0hH6/TuYOHQEDCoqLsGQdpXoF4NBA0eZgCQPC1n2sN2YdEJR/suvAlO++NCrcDreCmN4dKr8mPAs1E+BYp65S2o+LU64M+/uIrsn1i0fiNgOAQpN4kw6JrcFSiGLSMFPChEymCH2aN/qeJB208WH4ZpBS6aUC3ADVlmX/dnB1qvPIPTcvGQliAh0WVDiU6maX3Y0F2Ccneg7erFM2n+akcuUIZOos+W3KtpIE5M/x1LCB6k5izhwd0WzohxqP+UeoFtTJPm0hrtQGqQZaZKiBhce2GDp4Ql5Yn3UPU+UAYsbldOLnVfrmvsE1jJk70enX4VwPL7koZBKbb8qrDih/Qxmeiq2PEeSEfIC7GZ3ZH/Lbg2QZJPf
    admin-user: AgB+Ur2Ebq+frpLGmOQ6YasrijcRJJ8l/VtCh15CSrlvEv5Ed2/llBQ8F+X4mSSS1fX3CVh6LKH5Z8ys1KmRyrAXiwD/HKbu2QU60ElVDQKiz40BwAYoORSl3vHB94SJlD3BuS08aoVSJibQf1ZJOTr6/0+fB+ploVAQcoNPBfEzEJy3W3xHBjbEt9WyMdjUxESCDC6c5DyyD9406DdpDX+J8qAHIX8hQiG9PHmEigBNKLmZ+Y6K+vwOq3iv2ZhBln+Tx+d0P7qqKr6nAY+B4wQkSTaVyKgCGPo2sgrcexF7yGS7hdBCrnRqznPwiWYRXdrtQv7yZ6RLLsYx4Rc9FEa7mmMaiGPOed4i9GNnD9u9ZzPpCiZVEGodopk1LiF3GDpISM1tR/1v3l3fCdjvlRpFhw9nZgT8nGDR8A3B47bFrTikSLFzHZBJYgI1jysIyDO5IGKGQS6bVjX/VbcCZIZd/CtqPky/OfO8i+ztRkJv+Fj96ZB4Q0y6blsyOmXpyK/vAns7agH+53lE18GlYea1BbWks6jTCq81b2LTa7w0z/qm9M+J6l6NgGrmzrvhDV+70sMsnznfamZ7TwyrqsDaHGxTT6jMQuML1/oifNnGQXaV24UMOIMDPDwLEwxNJtHdDmr84pQiq5LV6EentP60O6ZG2bHSleVrQ8yA4gbUWOflRj+uug+iN5jyuB9U4lCV0bPTqA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
