---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: flux-system
spec:
  encryptedData:
    admin-password: AgC/TvfAoqdKGc8GjOCM+RvV2QzFO3aneZxEHy+/BYBu+LVqzE7vfZgYwWZXNjxi5SjDm3Q6e3FTjFwAJdOZT4d3RIvfEKnsRxl9Bq4ShyXtWX7QrFqvejdrZIXWaoGLVbAuGE4jRKzPqu48IqU3svhgf7WScj4jPNM9vEKEuyD/Wy+/sSdjo5FtOsgCCCTdMhNpJSKDB5gH+Gh/l1pCEooYox/coXxmWjuvgkVoMJLpG7KB4kT53xFRo0VTjFLO/qYgHToBr6bwQ0/G73bdak2PgRc9a0yH4/C1RMPWYwqjm1aTrJY+R1RDVsM9wz+Sr/i3XQ7tohWarPtk/fdr9N5jaGKOMiKhzNbB9dCgaQbi0TEFVp07B8nNhsKd1vuTbmGYdKFwoCRU7Fmy0bqaW5AFB95o6TDpKfTGRx5jAPQPK4PgmIKNlawUCsXTktTEAZ6e224OH3rNfIutMxY+jZdsDSl6oyo3Zr0TXGZZRNpLz0BxXMkrIKXKAbxGzQ4A2uXV8rkM8cuPsaIz1FsxyzZKDqJ9bsZAom+B/qzvzNIENA4tmNknhU5+MIIY2epJuTONl/JYKCHw3idJLqmbPP5Vz35qIaHw26Rh3UfkkSLo38tnyfyGZxyisnH2nUFgllh8JIABnhE4xpi6/xeqPMrcNvAiqwO1Gje3Ijm0wOCgZ+rup/MMm7Tj1p6vdzn4TXfaUFuwynOgu3ZVplNu4ZA/54oysgzLIUnsTw==
    admin-user: AgDCJP9Lx3clk+y8wbR9Wuj3GOKroTrvj7PO0U5zCXHek65OzOH9IPe6ZPczDfD18/zt2jJxPnx/OtO/+bCPFSYmFi+PZXEa9+G1gZzkcxOmR8NhuC/TvQDfLQeH9iZOuAU3IGcNVjxtAscXqQM/JnBwT1RFcjZK7Za3gl2WCNIjSJ0OB7HBIoLAJ8U5dmMUY1oiJmzP8VcN1jC+tJH6yu3jc8X9wQRw6Jd9h0dHdoww1TocoXbBhxGa5Yu09/uAgjOD9tSCICrTyj8QaofJGPD2YEkV9QDeGUsO4c5TwCwJn7uQcWiLoVlaoXI+LSkEz9vwK4MaBBYRBwpHpDqYtLl6fSdYSI0MYtHUKol3pOgPFBJf00WgZxELchmS+VBuMhx4ADpEYbt1I2nEHeyU4DkkEllUtZR1OhyHzSWTMDggkudVj+LR1t+NHuJ/x7vrZeC48w1AgQegAEj47vbSR0utlByVsYaj7XuYuNgntGxKaYZVrymwNFn6RCvR0dpapvnuI5F5uA5OIumXkiYLev7npSk/qD0eN9a0a8qePfZo4S2p5pIAPNJ7PyvAkAKlrF9xkP2WIz8TLcIEbuYU5BlQgknFXbnO43yQOYP9I3rH81jWcuHy9DVMZj+v0m4E4hv4YrixoHm4bLzQa4CjRKrJRMcAZunhQbPCxHWFuV/IdfAbudsERL/P5n4VUjHuwcob2pfouQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: flux-system
