image:
  repository: grafana/grafana
  tag: 10.2.2
ingress:
  enabled: true
  annotations:
    meta.helm.sh/release-name: grafana
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: grafana.marokiki.net
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
  path: /
  pathType: Prefix
  hosts:
    - grafana.marokiki.net
  tls:
    - secretName: cloudflare-lets-encrypt-grafana
      hosts:
        - grafana.marokiki.net
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: prometheus.flux-system.svc.cluster.local
        isDefault: true
        version: 1
        editable: true
persistence:
  type: pvc
  enabled: true
  storageClassName: longhorn
