apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 10m0s
  url: https://startechnica.github.io/apps
  timeout: 3m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 1m0s
  chart:
    spec:
      chart: netbox
      version: 5.0.10
      sourceRef:
        kind: HelmRepository
        name: netbox
  valuesFrom:
    - kind: ConfigMap
      name: values
