apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
configMapGenerator:
  - name: values
    namespace: netbox
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - helm.yaml
  - pvc.yaml
  - sealed-secret.yaml
  - sealed-secret.netbox.yaml
