apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-pvc
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
