apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-pvc
  namespace: netbox
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
