---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbox
  namespace: netbox
spec:
  encryptedData:
    postgres-password: AgCuk/KQa9t2TZ5/FkxiT6XtWypkvuBPyrT0cVLKtuvFf5cEAebDDlE1lND3903fp3JnjxFrhGXLsbTDaDd5BNdfZPR/7DuW5DgZ6n/a8NzKLEzAmaMTMalX7yQDK0Iuk95HrKUYIIyrqCar0nt+4R6NF6fBIYZaZytzM+mPA8z67vguRqnC5klhiLe7UOlswaaW0+Wjn6PDZcFB9ecwf7fxlF5y63uezoP9mjAPPqNBxIjZ90u0SKldcyI95jIgqb/zouBnVYCz/eB2YnmCiaSmYH65IH3I769aa5quQ2rMsZFwugCA2raNt5QFyhYgle6N756JqSE+XAoFz+Vok0LUq4q5At2sfoQjVoHzpYZOMOsfhqelwmK52L49UVBNXQVKn8FF7l8t1QldAyuMrg0bwa8RtT1PoD66gHL2BHZG/JYmJnZEZrvOJ3e8fo0tyJs6QtpkTvRVaKUtTG/St1xsuGCfmTtRoRvXP9x5U6aBcolOj/y4VSntvrXal3OnqYmKr0QqDNh53dc25IH3sNAtscUpCmbaVk4yUTKDtP2bwnCrfYOPgAi5hlllk1LdsQbW1NE4dCWPVUbczLf8ViulJo2ST3czHeiA3OF6YqTvY/QOyPFP1oQ0r3zgFg4H18qlMGymhrfGfkJqdsf7QrsnN+YfwU+kKnoy7+PoVmmcJYr5UUMBGaL42SkVAVF8WaQXMuqvN/kW9jWsqqKa
  template:
    metadata:
      creationTimestamp: null
      name: netbox
      namespace: netbox
