---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbox-secret
  namespace: netbox
spec:
  encryptedData:
    postgres-password: AgAkNE0Bzql+tm1uo1jvIG45yOB+cKWCaO6OJGnvGplslYW+S2pXsY8yOVZOVoDPf7usJSqorwBjkfL/HkGaQ/geScqjBtcKKjO3480YQ2h8yeKBys+XVLne+Cs8WOCgSmZSS9v6prgv5VjvVT+Aa+vKAucWbCH3oz4wG6nLj3ha6X85NmHbo6FzdRFSIJmq7GgoZH9fBZ8COLwczRCW94h5EHKtUSvsjeD7iFhUUfzfX5Mjt62C1sK2dEBS2jzhpsNoHRnbsQuXcPIoA1Xt59da1ylx/dQdo2f9Nid3IsqVzN6ppCmdqxwIQchMLvzKtv2OmDG07WxyGkEAXrGEdHey/PU3lOhKLUCTcsLGTr1vgFBoFG3iVGKQHBAi24E+T0RCsl/lTyZMOOU1qPw4umtC93J3XF1FbP/ds4pWJlRkMrfOc9Mpdk4AAW6jTSLyVdu1E0N1FaYpBUHiPg0x9dwOdEFLQKn/ouMZQPkklsyqRS07j0AgJcYnkmYFY6p7AzqOsH7tI7NU/kBTv666YQtmrtZ/DVrWd/NzmdP36rShczzOim+T64FIWzmNPNLG2lcFIWDCaW1+4DNKfXfTm1m+ChNfp306VxNJk3yY6RIvC+91bFcqyU2SqVFfTE833ZEKcXNt8Olb0bmUmp5kFIurEfga+l2PFhsbk0uHSYz3MJDcnAD3aB14DFp1Yas2PjTzoN+H2v6KDMfK1S75
  template:
    metadata:
      creationTimestamp: null
      name: netbox-secret
      namespace: netbox
