---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: netbox
spec:
  encryptedData:
    redis-cache-password: AgBZukIqESjp2mHI+5cdnJrtZUFOkqXMpSfZAQjiQriI3X5778jCMxMQzowwEkg1VSR3sNMyqkAy9Ka49W75eW9vJeGrz45f5HY1wiywBpD2PjqQSu7CHySeTWvE3g01e33a8b6pOYE7Zu8Tkzg9CEX6S8NL78TeoBYdskLt2ycLR5tEx0MaD8ZwSBVQpEQxl7Qt7vuWGkIt5WpTR6b21JGtz7i7D8Jrti4CzmJ8p4ITWTI3ywvHvaLwh1lCG2WmXj95AEZavFJ3oFnNZ9hvl7v0hUxoGvkmu19ytQ1clIe+e1z3SInbhrTmqyzf8bVOyrThzdCq7Qt8FXJrb1HRHeNQ36j52gY1b8LwQQ1pnIFAzZgSMuDTjnFdbFu3jqp4zjbQBDksKB/ud5mNsjw7J/Vo5mO7j875/3oADmhr16z7bUXPahhIJMqdFwy6w/B49E3CszSBeDdWPnspwxvBr6mmMQQE345MxH+DCtshXoBGo08VVOxSPdn8utRJuWVdXtKZZWxsxWkasMVBD+hL9WCfiGzru3XaHBRE91Dmwz5qMbD23i+7mpHruiiKei08efV3Ryu/YHrtyhv22BssCyf3aQ2OdgN3GcKFrpY2HG9cVr7V6UWgPGOH9tAFS6c+MML1aFKjGUtoxmHj9pxCIEqDKWbKFb1Oryf8kUe2wr1dPSHcVQ17yYKDlzbVEbfjswKjQeDClxx0YC+FM3tc
    redis-tasks-password: AgBX6G9iukHxIkhO1bdalS9xDyIvE7NCTLOrlPjXVJFpGP2rfGclpNjuJFIPySKp3WDMSZLpFHJD19xcJ133WL+HFUZyIblFVPfLD8ABcKsqQ5wQMc3jSFXBtN08txq1w4mepTtWNyMP8IlVmuOAgA3pvDGlkgBXqJY7WvdqCIBE4ZLwqUe47vQMZpxSWnM0PdFLy+o7UnGdQo4x6vYQkO8YNiNOTIrOFJGcs8lan8sz9hYkDe/JX9wDRrOtb1o9AI6vgt9Y+wRAk+pnPXpFXBBniHUHghhlzEh4P0a7FCyceQj8Y3sF3PU9R25oBVgOyUfj2gVYOU7VMqAL/plWjBe7ntxHPKvvpFvvZGOTykVqXzZcSZnNNAunktzdFRG06E/5VTYs41T4D5w/S9fg89wSItZdBNUAysMu6kJSfbSDhbUqZtJ0kK38rHHXZYCPKHxifUV6y3O7lcQ5ULXE0qsmxnzFremnlCJkLXFwEQ7QWrfyGuFhZlD3jx2rfxhlbLHYpEy71u+U2CDvWiuFGlZIzr0ZHSHhprXPuic7kDDgYUgqBRrfnTLEqQanIwsMXtjeLcMwhJ43aZ6uOPPuwhCVImskc6JzNokP8H724njzmWqHsNN6idEF06VNS5cIFuMnsGkAAziPZNHwA25C9sUad/sEf1CGvTe/FBJEzmVRXU1H9pjDPmNSOKKqwiI3D6fF0tfWGc+jHe45L4Fi
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: netbox
