---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: netbox
spec:
  encryptedData:
    redis-password: AgAlO3qfPn0AO6npHJYjksN99QqsJQVXPco2riyWDrYLpuoVmshK2t1Og0O8xcTramhKPzIuBz2TaqvdiuG2ZPbU82HDUtjs9ZG+Qaorm2pyjpkn9qn9Bc6GD8J6IXyE7dogWL2+K/LcTrhXfhfgPDilSxhf1iflVm3MOky4i3BSseRZULr5SfCOnUeMnrm0cXNkmD8N3D8F2MNgwDpH9EhmY78ZY2TATFSC96bSnvkPyrqlmOQekIYuM0gZNeKB/bqMhTRRZ8hKmRd0RmTSTVdl9mnqDu6y8EZb46VWHjnRktTyHxI+KCQAldaZaAeEXmYPBMa2tIt5PdzzxBW3Sm1YZGaeSLhj0fvKmPlFdDCOmzFs8iKgtoevekuIoPCOK3CAakx+0jKizzpwRTxrolLEZI86lRjG/pQzmgTecG+f+bEIF8PkO4m6XlcP/bwV1nep3a/uDC4xe7S5Q6O/NnGlHEFq5m/5edyD6Qs5dBCxhe51dkA0hsHHetDvntBfNsDDYKCAaVMPev+n6qSY25JZBylQOXkepMiVYri1xSJsUBAXlFn3PSgRy3ThZGXxe23ySYL38SeIzofx/LPcuO/uOXvMt4uoUtqKNGkmXyDJm7vST/lOGg2Rsa3Q40Rj60qFDlH+/Uv7zKGYGEi3Orn+hOWS1LepVR6G2RXixYmfGf3rE20bkDXrUP+SGdVzLtJ7K3x7pUlY3rls05NR
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: netbox
