replicaCount: 1
dbWaitDebug: true
readinessProbe:
  enabled: false
image:
  repository: netboxcommunity/netbox
  pullPolicy: IfNotPresent
superuser:
  name: segre
  email: admin@example.com
  password: admin
  apiToken: 0123456789abcdef0123456789abcdef01234567
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kinoko-1
postgresql:
  enabled: false
externalDatabase:
  host: netbox-postgresql.flux-system.svc.cluster.local
  port: 5432
  database: postgres
  username: segre
  existingSecretName: netbox-postgres-secret
  existingSecretKey: postgres-password
redis:
  # enabled: false
  enabled: true
tasksRedis:
  database: 1
  # ssl: true
  # tasksRedis.insecureSkipTlsVerify: true
  # sentinels: 
  #   - redis://redis-master.flux-system.svc.cluster.local:6379
  #   - redis://redis-master.flux-system.svc.cluster.local:26379
  # sentinelService: redis-master
  # username: segre
  # existingSecretName: redis-secret
  # existingSecretKey: redis-password
  # ssl: true
cachingRedis:
  database: 2
  # ssl: true
  # tasksRedis.insecureSkipTlsVerify: true
  # sentinels: 
  #   - redis://redis-master.flux-system.svc.cluster.local:6379
  #   - redis://redis-master.flux-system.svc.cluster.local:26379
  # sentinelService: redis-master
  # username: segre
  # existingSecretName: redis-secret
  # existingSecretKey: redis-password
  # ssl: true
persistence: 
  enabled: true
  existingClaim: netbox-pvc
service:
  type: ClusterIP
ingress:
  enabled: true
  className: nginx
  annotations:
    meta.helm.sh/release-name: netbox
    meta.helm.sh/release-namespace: cert-manager
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: flux-system/netbox-basic-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: netbox.marokiki.net
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
  tls:
    - secretName: letsencrypt-cert
      hosts:
        - netbox.marokiki.net
  hosts:
    - host: netbox.marokiki.net
      paths: 
        - path: /*
          pathType: Prefix
          backend:
            service:
              name: netbox
              port:
                number: 80
housekeeping:
  enabled: true
  affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kinoko-2
worker:
  enabled: true
  replicaCount: 1
  affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kinoko-2
