replicaCount: 2
image:
  repository: netboxcommunity/netbox
  pullPolicy: IfNotPresent
postgresql:
  enable: false
externalDatabase:
  host: netbox-postgresql
  port: 5432
  database: netbox-postgres
  username: segre
  exsitingSecretName: netbox-postgres-secret
  existingSecretPasswordKey: password
redis.enable: false
tasksRedis:
  sentinels: [redis://redis-release.databases.svc.cluster.local:6379]
  sentinelService: redis-master
  username: segre
  existingSecretName: redis-secret
  existingSecretKey: redis-password
cachingRedis:
  sentinels: [redis://redis-release.databases.svc.cluster.local:6379]
  sentinelService: redis-master
  username: segre
  existingSecretName: redis-secret
  existingSecretKey: redis-password
persistence: 
  enabled: true
  existingClaim: netbox-pvc
service:
  type: ClusterIP
ingress:
  enabled: true
  className: nginx
  annotations:
    meta.helm.sh/release-name: netbox
    meta.helm.sh/release-namespace: flux-system
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: flux-system/netbox-basic-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
  hosts:
    # - host: netbox.marokiki.net
    - paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: netbox
              port:
                number: 55380
