---
# Installation
- import_tasks: apt.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']
- import_tasks: yay.yml
  when: ansible_distribution == 'Archlinux'

- name: Create Directory
  file:
    path: /etc/coredns
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Check Corefile exists
  ansible.builtin.stat:
    path: /etc/coredns/Corefile
  register: coredns_file

- name: Copy Corefile
  file:
    path: /etc/coredns/Corefile
    state: touch
    mode: 0755
    owner: root
    group: root
  when: not coredns_file.stat.exists

- name: Check hosts exists
  ansible.builtin.stat:
    path: /etc/coredns/hosts
  register: coredns_hosts

- name: Copy hosts
  file:
    path: /etc/coredns/hosts
    state: touch
    mode: 0755
    owner: root
    group: root
  when: not coredns_hosts.stat.exists

- name: Run coredns
  shell: |
    /usr/local/bin/coredns -conf /etc/coredns/Corefile
  become: true
