---
# Installation
- import_tasks: apt.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']
- import_tasks: yay.yml
  when: ansible_distribution == 'Archlinux'

- name: Create Directory
  file:
    path: /etc/coredns
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Delete Corefile
  file:
    path: /etc/coredns/Corefile
    state: absent
  become: true

- name: Copy Corefile
  copy:
    src: Corefile
    dest: /etc/coredns/Corefile
    mode: 0755
    owner: root
    group: root
  become: true

- name: Delete hosts
  file:
    path: /etc/coredns/hosts
    state: absent
  become: true

- name: Copy hosts
  copy:
    src: hosts
    dest: /etc/coredns/hosts
    mode: 0755
    owner: root
    group: root
  become: true

- name: Killall coredns
  shell: killall coredns
  become: true
  ignore_errors: true

- name: Copy Systemd Unit File
  copy:
    src: coredns.service
    dest: "/etc/systemd/system/coredns.service"
  become: true

- name: Start CoreDNS
  systemd:
    daemon_reload: yes
    name: coredns
    enabled: true
    state: restarted
  become: true
