---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install coredns with yay
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  become: true
  become_user: aur_builder
  loop:
    - coredns
    - dnsutils
  when: "'coredns' not in ansible_facts.packages"
