---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
  when: "'yay' not in ansible_facts.packages"

- name: Change permission yay directory
  file:
    path: /tmp/yay
    mode: 0777
    state: directory
  when: "'yay' not in ansible_facts.packages"

- name: Install yay
  shell:
    cmd: makepkg -si
    chdir: /tmp/yay
  when: "'yay' not in ansible_facts.packages"

- name: Remove yay
  file:
    path: /tmp/yay
    state: absent
  when: "'yay' not in ansible_facts.packages"

- name: Update yay packages
  yay:
    update_cache: yes
    upgrade: yes
  become: no
