- name: Install package with yay
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  become: true
  become_user: aur_builder
  loop:
    - kubelet
    - kubectl
    - kubeadm
    - docker
    - cri-o
    - cni-plugins
    - open-iscsi

- name: start and enable crio
  service:
    name: crio
    state: started
    enabled: true
  become: true

- name: setting for crio
  shell: 
    cmd: |
      cat <<EOF | tee /etc/modules-load.d/crio.conf
      overlay
      br_netfilter
      EOF
      modprobe overlay
      modprobe br_netfilter
      cat <<EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward = 1
      net.ipv4.ip_nonlocal_bind = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF
      sysctl --system
  become: true

- name: enable kubelet
  service:
    name: kubelet
    state: started
    enabled: true
  become: true

- name: make cni config
  copy:
    src: 00-plugin-dir.conf
    dest: /etc/crio/crio.conf.d/00-plugin-dir.conf
    mode: 0644
    owner: root
    group: root
  become: true
