apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kubernetes-dashboard-basic-auth
  namespace: flux-system
spec:
  encryptedData:
    auth: AgDW672Y9+2QGfHILAQljJDQq2DTLOJZ0Rt4xTX7UlK9//OGcq/+DFJ+G2ukQeTW5HD/y9HhKUAgBHG33VhowZlsLh5RiZ7cexS505UlThD7CbbVOkcpDLWjYc6HdUm3+RQByF+wyZn4hpxvZ2Q0PkkzCd2xHaVYHe6ehpL5WqE/caRoMe/t+5lIhsrSr0vopmOXos9OttW5qZ7zGXRdcib1Vsjzi7L4IA01vZPLvpH2Dawo+VOQRfs0MRljAkahdSEu3MYjOeBaXeOG4n2/tm6WC1HOSv36vg2whTLuytrLFvXbhYw9COETKeP8xNWLY2flse/T6kLc4H53IsbwQ4GP9Iiw1JXP5XRCfbK6oVMCU1ylIzx0xAImfYQ/jyuqNwdkaU1jJ/bv7I1HYbi59C3yWdezf1erYgz3tpFwWMmna734llafBbyzAJf+sPhqIJ0U5awPx7oPpmE3fDcmW821OWXR+0Mc+hqnKlwJOs0adsss1+y2kLB5SxpRx+RyM27J4XDczRBCUyX1wgTURiPs6BSMQxVhjcvZ2VnVjBd+IUdobJZugalFkZaoc3E/+2TZDbifcTXRc475nl0+nefDZY99vlx6bU0VQ3phtaGnkdMT07Vem0/SKv9SV5H9BolPzacBU3ZDEW6OElcyJFzdwQv6yZjQh7cm69MeE5bTe64hq4pzaUWUnLuPTaC2eWCLBRtQqQJfVPj5V/1qEj21YuUhuVt/dvv3dbssFuwK31PAfGGo8OnuFyd8OQ==
  template:
    metadata:
      creationTimestamp: null
      name: kubernetes-dashboard-basic-auth
      namespace: flux-system

