app:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      meta.helm.sh/release-name: kubernetes-dashboard
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: flux-system/kubernetes-dashboard-basic-auth
      nginx.ingress.kubernetes.io/auth-secret-type: auth-file
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/hostname: kubernetes-dashboard.marokiki.net
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: letsencrypt-issuer
    tls:
      - secretName: cloudflare-lets-encrypt-kubernetes-dashboard
        hosts:
          - kubernetes-dashboard.marokiki.net
    hosts: 
      - kubernetes-dashboard.marokiki.net
    paths:
      web: /
      api: /api
  cert-manager:
    enabled: false
