apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: internal-dns
configMapGenerator:
- name: internal-dns
  files:
    - config/Corefile
    - config/hosts
resources:
    - service.yaml
    - deployment.yaml
