apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: internal-dns
configMapGenerator:
- name: internal-dns
  files:
    - config/Corefile
resources:
    - service.yaml
    - deployment.yaml
