---
apiVersion: v1
kind: Service
metadata: 
  name: internal-dns-service
  namespace: flux-system
spec:
  type: LoadBalancer
  selector:
    app: internal-dns
  LoadBalancerIP: 192.168.220.152
  ports:
    - port: 53
      protocol: UDP
      name: dns
    - port: 53
      protocol: TCP
      name: dns-tcp
