---
- hosts: all
  become: yes

  roles:
    - role: apt-update
    - role: yay-update
    - role: networkd
      vars_files:
        - ../host_vars/{{ ansible_hostname }}
    - role: resolved
    - role: sshd


