apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docker-registry
configMapGenerator:
  - name: values
    namespace: docker-registry
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - helm.yaml
  - registry-pvc.yaml
  - jobservice-pvc.yaml
  - trivy-pvc.yaml
  - sealed-secrets.postgres.yaml
  - sealed-secrets.redis.yaml
