---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-postgres-secret
  namespace: docker-registory
spec:
  encryptedData:
    password: AgBc0gvlLhUUEhaQ3KoHYE7gW9jDK3OsOYDK6rqzWnaKG0XcUvfmxq3r+LzXLXpRTEsLjeMHqkFTeNWqHOJapyauEbZ2dZ8Qc5iA6Qbm18cW2G/eicfx/UYM1cuodzQ6pLlNclzyyyw80se/6Eo5I5O0tZJvZj0Cb2VN/S9vX1UaP91YB7IcXCg71t2QgDi86lb+7hF5xGc2y3AkwH0c/U1ZOl1jOzWSztbljEujHwp4/A4L2eUxQJsD3ueUHqAKtwM7mSCSPqn9HA9r4aPcyFhofo9njeYuDu3K1xU7aBeXV3/lWWZxR7m5ScEfurHxTIVgK2wasHkZaN6a0pm+paWQtCUs2VSeC7fsn2OCv6A4z7t/q0qngCg3w3kA+ERUu/2HBkZd4CqaStrg8GktHgaO2WVyR+aGACBEHx5RpfmqPe6c6cg6MBT2A01RgvCu+MHN5ruH3Wq1lXt8wFLuNWb5Kh9emvjEy6hvAhAI6RSMNRW3p4gx4aIwbGDcRTM6tUNQQcm+OIGcC2ZmShHwP7Ow27TqH9/iHhjHgraoYF8YCZSK118y5I/nU8KLU6txM7aVi7iWyi6a7nLI2KlUtJFNUHB7MpXDxs+2LNz6btsbtFFB1W5lY6tXzQjQl082+2n6WGzB5kw8tiJai67z0RfZ1JhE118wBgutp2607UjAJllYDLIuVKshdjfwrNfCqH1TmrZhIXsbK385mucp
  template:
    metadata:
      creationTimestamp: null
      name: harbor-postgres-secret
      namespace: docker-registory
