expose:
  type: ingress
  tls:
    enabled: true
    secret:
      secretName: cloudflare-lets-encrypt-harbor
      hosts:
        - harbor.marokiki.net
  ingress:
    hosts:
      core: harbor.marokiki.net
    className: nginx
    annotations:
      meta.helm.sh/release-name: harbor
      meta.helm.sh/release-namespace: docker-registry
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      app.kubernetes.io/managed-by: Helm
internalTSL:
  enabled: true
  # certSource: auto
  certSource: secret
  secretName: cloudflare-lets-encrypt-harbor-internal
  jobservice:
    secretName: cloudflare-lets-encrypt-harbor-internal-jobservice
  registry:
    secretName: cloudflare-lets-encrypt-harbor-internal-registry
  portal:
    secretName: cloudflare-lets-encrypt-harbor-internal-portal
  chartmuseum:
    secretName: cloudflare-lets-encrypt-harbor-internal-chartmuseum
persistence:
  enabled: true
logLevel: debug
database:
  type: external
  external:
    host: postgresql.database.svc.cluster.local
    username: segre
    existingSecret: harbor-postgres-secret
redis:
  type: internal
  # maybe bitnami/redis has a bug for redis username
  # see https://github.com/bitnami/charts/issues/7709
  # type: external
  # external:
  #   addr: redis-master.database.svc.cluster.local:6379
  #   # username: segre
  #   existingSecret: harbor-redis-secret
chartmuseum:
  enabled: true
  