---
- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required 
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install packages unique to apt 
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - unar
    - python3
    - python3-pip